apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-ddns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflare-ddns
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
          add:
            - SETUID
            - SETGID
      containers:
        - name: cloudflare-ddns
          image: favonia/cloudflare-ddns:1.15.1
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "3000"
            - name: PGID
              value: "3000"
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
            - name: DOMAINS
              value: home.tartarus.us
            - name: PROXIED
              value: "false"
            - name: UPDATE_CRON
              value: "@every 5m"
            - name: IP6_PROVIDER
              value: none
          podSecurityContext:
            fsGroup: 3000
            fsGroupChangePolicy: "Always"
          resources:
            requests:
              memory: "50M"
              cpu: ".1"
            limits:
              memory: "1G"
              cpu: "2"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: cloudflare-ddns
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: cloudflare-ddns
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
