apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: gotify
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
