apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: immich
data:
  IMMICH_LOG_LEVEL: log
  MACHINE_LEARNING_MAX_BATCH_SIZE__FACIAL_RECOGNITION: "1"
  MACHINE_LEARNING_WORKER_TIMEOUT: "300"
