apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-machine-learning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-machine-learning
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        readOnlyRootFilesystem: true
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-machine-learning:v2.4.1-openvino
          env:
            - name: TZ
              value: "America/Puerto_Rico"
          envFrom:
            - configMapRef:
                name: immich-configmap
            - secretRef:
                name: immich-secrets
            - name: IMMICH_PORT
              value: "3003"
          podSecurityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "Always"
          ports:
            - name: immich-machine-learning
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: immich-photos

          livenessProbe:
            tcpSocket:
              port: immich-machine-learning
            initialDelaySeconds: 10
            periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /xrpc/_health
          #     port: immich
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          resources:
            requests:
              memory: "4G"
              cpu: "2"
              gpu.intel.com/i915: "1"
            limits:
              memory: "4G"
              gpu.intel.com/i915: "1"
      volumes:
        - name: immich-photos
          persistentVolumeClaim:
            claimName: immich-photos
