apiVersion: v1
kind: Secret
metadata:
    name: authentik-pg-user-creds
    namespace: cloudnative-pg
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:fuuRNtIrqwNH,iv:NjfsRGwChpWM4c0To4EEiEVF4lwv2PflbZ5TcEWU7YA=,tag:KyVWTpUFhQo9tvlQiNxjZA==,type:str]
    password: ENC[AES256_GCM,data:SwZQhY6BqGiJC4ZDA27l3YRKnNbSnzM1bdaywvZM1Mo=,iv:6T7PMNNXlGaLyxJ9MOY0tjITslkK7jmhiwPycS5kkC8=,tag:ZXl/vv4oo/1fQXjaSMt9ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMGE3V1ZCYTJKRi8zMkcr
            S2JlZ0VQSk5zNS9MNFJKTmptZVh0MDQ4alNVCjg4WTB6Uk1DNE1zZGhySGRiWVRX
            VTF0YzRzMXYzTFl1d2Y3S0RKMWRuWjAKLS0tIDZCaTZ4VlpwKzd1dUtPcThUODVj
            Znl1OGZYYVRzbnlEV3J5RGo5bUlDOE0KGp5xaG7ljgbo6fbB90OgAAuzC0uy3xr2
            Lj8CVL3UkxbDwcH5JbNBmYWlYMWJ93X75TriieCz++o1CGHAp38mIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T03:41:42Z"
    mac: ENC[AES256_GCM,data:lr+9U2rpaYjgNndK3b5K+DPPnudKtzLQxT40B5kplo3yZ2Dzu+/BoY7qWMReFqsmasrIBzPniCUwghLCGg+OOhhYzA2WOdXs2SjHmzwRykQjrNL+UA7oKYGIIobCfAwXNDLi/Wpiafb0CLrAWddPRV3Uxn0pjgI/cyTMH3xJ1O0=,iv:WkbM3RQzjP22aPmhR6rssXUs5W346n9gVdclif1wuhk=,tag:0dVtOQuVsTtJPJbFF7BQzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
