apiVersion: v1
kind: Secret
metadata:
  name: harbor-pg-user-creds
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:L2vamNnK,iv:McrS7WEi5oYs+g4E3I3fJruCJN3I9B6QYRJ2ZGWxNb8=,tag:UbsstCbxDghz6+u9hwXkBw==,type:str]
  password: ENC[AES256_GCM,data:+e/TqIAedlm/wWAh0l733oLrnvxzxm1gV138KBJpzVI=,iv:TqkoMPVx2/SL0VU873QJ9PIXqmvmbVwi6D3rEzclR20=,tag:T+pUIQGXJbYyf8fS5r0hvA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUW9sTmMzSlJIRjRzMTRD
        akFPeDhHaksrVVg4U01YY2UzVzU3Sy9oa0dVCi9veEJXRG5nWTNRL3dFclFvZUw3
        M0IzQnhOdzdkbmhRU2JrYWp0NUtIVGMKLS0tICtlZTZyK0tsd1JJdDRUUkZPdnZV
        d1F4Z2R0Vmd3ZklhSkZqOXJPT0RWQ0kKoVExoXxdAp5ACTqaKFR6BjuSG3SGP9VW
        mg1vUqbxzS8zUDXipvxxnyo6QVhpWnfCuZeGub/WDomGIIhRRMaRHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T16:37:23Z"
  mac: ENC[AES256_GCM,data:fFhmdz7z5iJzPf7UNchn1c35Dr9y8XnQ8Wi+IkJCi+XM7JjR67hBK+edqcoY9YSODTEogNGQdLkdcu6N033qRZWePcJuDuEdEy+cjiWMt0GPsoC/L5VsST8US/R4AVsbcPYxgG6XZ3sMypqnBFZyz2uFi+ec5pfe0yUDxYVIEwo=,iv:DSkTmY9Ij7gZEObj7IWVKBoddhMn+175DPeuf37B5A8=,tag:e89W1K5/C3V8ELrYVhaPOw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
