apiVersion: v1
kind: Secret
metadata:
  name: immich-pg-user-creds
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:FdpNDDFd,iv:mqVUC8TjlGfwodVdIwPus61FQGBZ8qsu6ZbxdFpmaRs=,tag:z+DQGwowdXG/FsYiUsgMKg==,type:str]
  password: ENC[AES256_GCM,data:Cfq7okZQqte9ruRdVXK/1aCRqtA3lftw,iv:UNx+YDxQHozqiNKeL5dagBwsIMkBkgvAtDI81z17rnU=,tag:GDOa5WIkHqoAtaj73UkY2g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMU8xUUY3cDlIR2ZLTyt4
        MEc3QnVtaXcvRW16OCtOQzVwWGcyS1lOY0RjCk9jVXpVNGZVN2s5Y2VqUkZPWHN0
        SnNUVEdleUxGQVIrd3l2dHozTWxheUUKLS0tIFdyWGxTQ1NhUXhaM0ZVS0ttQmtD
        NERYakdnR0dNTzZ6ZitZQ1RON1VnVlkKuAt7AlVG0YnQapOAgJokl/b2rG+yMUe8
        MkAtXpI0AfK3yZIahwXCjTqRkYA9ri6nJO5qTVS98O30ui/0tDtW3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T01:32:09Z"
  mac: ENC[AES256_GCM,data:PXuPPtkWkhMdZtu7zJex/LpeiUD4K+iMXD9/RQyj+2ayimIkwoLAKFMwpQ8PviMJDdxwHz6gyzo7VRDxhtBD5x7sfhp7u8o0OgtDKYTiurclmImLtztzjZr7Q6Fe+b/wOaSaLoqe79+99243gTbKmGxL2fEF2tCXpxySw7RiS94=,iv:YUADzJXN3Bv0XIg1RiaRO7Vnx/9UOnGuHajkP3S1U+0=,tag:3rS4WsezrPKLNCajcTfEZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
