apiVersion: v1
kind: Secret
metadata:
  name: immich-pg-user-creds
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  username: immich
  password: tBXnxMIArNmhvmfKXVkNG8so
