apiVersion: v1
kind: Secret
metadata:
  name: ntfy-pg-user-creds
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:/VGvPA==,iv:pB3RtKEPsWBVtnC+mGMeIQaqdT9v1Lr9ktXi5fKq7LI=,tag:ypG6x2OX8/gSDP2031fy+w==,type:str]
  password: ENC[AES256_GCM,data:qn834tDRYcvKFKB9KvlIqZ4Tx3Y/ylwyT98NkCbZsrI=,iv:gk8344rX6VFNvfRkt4dk9xh2yLCfFFslI7K19wigVks=,tag:QK3AVa/bvDovbs1GAvMU0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYUhPNjZYWFVyS2d6VGNU
        RWpCV21ueW5MaHY0L01Cam82a0NOVWJ1blNzCjVERHAyQ0F1SUdRT1k4ay9ad2x1
        VGJnZ1JHNVNjd1JtcVRkRElvVU1XOEUKLS0tIHVwR292YzNlT3JWeTVXSVJtd2FJ
        WFdKMkx4N3Y3bXBhdGt0d255M0VINU0KF8TCmrMvec66zM4ElHx/ts7QcQooscBq
        7FQpnJZ7da67xK7n9oRCfZGx2nm0Z6Ldstaw9GLFMjjus8r/WBg1AQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T13:39:30Z"
  mac: ENC[AES256_GCM,data:p9M36wNOl0/BgjTsUspCIsetKpdTvINWtfD9UtU3myPkCqyz0BJAmN/o5xH01KZOtBMNhqisaZi40jgu+5gO8lXeqwTBF2FKhX6tp7oYghkyvac+xnikgeSIrbWNKNvobh3DfnFoJU1BKmJkbzX7hlMMW4I9OjaRzDel40oY3n4=,iv:w98H8G+o0kDf3+cy79xQ0+AKsZ9UpItHyl81tcQRaA0=,tag:Q152Yfn5X51TcqR15yygLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
