apiVersion: v1
kind: Secret
metadata:
  name: ntfy-pg-user-creds
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:DJmjlg==,iv:o0WhFSykU7hPfF2tMm1J5FXFUeNI5scS+c0vwV10/Lo=,tag:SODrhpgyjkDaiQbqGuwYFQ==,type:str]
  password: ENC[AES256_GCM,data:9tk8f9M02GwUugnSIINszIiZqQymrxM9dRQYOlBjWN4=,iv:V227W0IDDCotTVj4qidUAHuYmab7EA2vzklsgazttEo=,tag:PKj4yyDb76PQ5z5kydhMEw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQklUaExNdFM3aGIzRjdh
        NWJSZzFCRFV2OXUrVHFvYXJMc3pqbzRTS0FnCjFvQ1YrZnl4OU5iRC9tdW1mZm1S
        Ymd3NjRXZE5oT3ZyRitmeG5JZFAzS28KLS0tIGwvNXpaQlM4Mjl1YjZLTVhVZ2NO
        UWlwVCtUZUJkemZtSFlxTi9UMnlSV28KntiGFcLuXAVJQn7j6ETL+X6RiE/A6we1
        7ZfWK+3fD44p2hxm9iWghJuZnVchxVmxjb+wdkJO3VpWhHlvlU23Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T00:38:38Z"
  mac: ENC[AES256_GCM,data:NTJWThAma4AzQvF1tCh6463IYP8n0sOHNiywqLHkDqj9xlVahpW196wc06PY5t1iF7EtqkCZKa94Ng6+cCCTq7G66gWmVhlyl8WsOQ3+0FSuf2hUn9+cm3apbu42XlO3LVE8wae8lPngGZPPqoQnL/Vfs6HzhjSzYcfU++b7Mtc=,iv:derEwtfMZq/3TxuOK9sZGATdfWjB/XvX3mi+6VN7chM=,tag:tNYWIIM+NeBrBAaEn+mxNQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
