apiVersion: v1
kind: Secret
metadata:
    name: tranquil-pds-pg-user-creds
    namespace: cloudnative-pg
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:+gjTNJN3BDUEycxf,iv:30rB6rDBve6WSDDSKhL8D1X5Y6R0gBIfsCRSPLwBVfE=,tag:xNIdga0QqEGU26SJhOBOgw==,type:str]
    password: ENC[AES256_GCM,data:CoYBA98h7w8V7c3wIGs+6v0y3pZtFjFoOsMEA3jP0O4=,iv:J5VTp07TEA2WHh7u40q4bXkUZbTXREIf6VenpV4K0Mc=,tag:l/y/zlkdN+85Cn0cyWHtaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVHJUSnNEQUVyaTR4ZG5M
            MmF3eUdtYytXWlFzcDhJVDJlNFFMZkJ1dkRvCitSQ2ViYU5oTlRsN2NUcHNrdUFX
            VWp3c0w3ZVVHeHJKMVhscnRheWlLZUkKLS0tIGR5RnVtTTFHU014M0l4ZjlPZWZ2
            aXNEQm15YWRLUlFYVTJwQTJMTjZsdGcKDT1pXnIRLoDHarNSgaUQ0jSt+rVXukh/
            0OnOlzRXyUubDKJdixGZFAP6XcY7M6hf2Hx0UUZvcD+P7jB034labw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T18:27:24Z"
    mac: ENC[AES256_GCM,data:8S8ErK+C3iZmbuySifiV9+g4zIr4g3JW3dRmOQZ9VL8VRdJx5ZehKppAVzh/zM6/XXXJRe1qTme5gAE6jKPNQATHu5Jl8++BAUeYWIi3Ao4WEF8LoJ/JnwFYbXkCfPNwqYBu+DHb9XX5UoL7lUrt/WCRlYwXDdKAnziD942bLHo=,iv:DViVENRkSOAb4dNGYBo7uq6rv1nfcEibiTtStGtzknA=,tag:jLwoxylqshZ4RLWUMzPJ3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
