apiVersion: v1
kind: Secret
metadata:
    name: authentik-pg-user-creds
    namespace: cloudnative-pg
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:kkf7LVQ5mzz/hbqO,iv:+4HUKUurIxoG4hsFODXAZS1S86BqIuUhLJuzWsyNm08=,tag:CMI6luB6c5U2OkwGoYVW6Q==,type:str]
    password: ENC[AES256_GCM,data:UqXWWqRV9NZZSaSzqEuLFkLkNZPv9oHH82W/ZSLoCnc=,iv:hwZ66rSN/tZveuGGULeNkfuhxI7XdLyA590SECmvSLc=,tag:39sEi+eMS/lrRJD9rJZXLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZC85cmRPcVNnK0tyMkFv
            R1IvQlprdWRkRmpyUE93WFhSSSt0VVNvUjBvCjFpUi9CRlBzQnNtdGNXVFkxM1hL
            cEsxR2NGUDQ1STQ3TjBEOFpHSGdtTmMKLS0tIDBiZEpQR3hLUitCVDdHcFVxY2ph
            eXlicUdDQ1B3REM1R2grelVGRTBYYkEK5N67l8+fhMuiumYeMLAuZX2A/LuwFWFN
            0ISWdUEHHOArJdxXaKL9HrEEfYb4q6e60j5b8odarzN6dOGYa7rsKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T18:22:01Z"
    mac: ENC[AES256_GCM,data:0bTAdmOz8k3s7aAPu3RA0HxJ8RgZs6pJkMutPhmJ9rw4gj69OlejyGZPEpwMAiY9VQGksxwH6Q7WBB8E4YEW31jWLj+De4UcDXLd/7D6Ar9lrMscU5EZlyNajvh95QAm3NZTUyolye/1vBeSHbFd+k/kocaZ99uU2sT5NHWfDM4=,iv:bbwhptYBPN+3FRhEw1SKzHWXg7QvzC2eZY4wnydugOk=,tag:i22oVb0Mg3SVfA8EWn3IcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
