apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: hermes-agent
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:ZSK6h5Vs50PVATVJhpTLB1xc2PnUB5BEb8HoSTbX3j7ocPVuZ9vUab6DG38x9/8PFFhh0uJLvH6hjBuMImUgrG1zGM+n4quDDw==,iv:fvxJxdepmugcrzZ1K8r7Gh9N6Kfppx1erGLlAvreZgA=,tag:GFSMVkuafTddVsym99Bc3w==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:KhCLEB3vwtwG0BukXr17UgQJ2eshla8V,iv:eXXQjg82xm++SNIjcdhy4IcNelOd9xsL0ZqabKGMmCY=,tag:LwUBolOMPF+CEXO0MKA72w==,type:str]
    AGENTMAIL_API_KEY: ENC[AES256_GCM,data:hjBdKmXu1tLjdt7QIIu7Vy1kIt4I9s2pQIoJ6cgOFrcONkmltol5PGzOWwlCRTZPC8GmE2vQlkahKdN6tG9Y/hFoGK5VlGteNAJyvA==,iv:QcIaBs8SdLLVTkEjDai3MFyn7+0Ogm4SzkBmjb3TDGw=,tag:0UyRR7n5NKKUS1Jq/5apIg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ3pmYlhtbitTK2JwQ1Zo
            MXEwN0loVkx1c2VUa1pZQXhFQjVDeUtMTEJNClFJNDUyV1NXb0FBNERyN0hPOHZZ
            d0MxeGx4TWRpQWNTWDQ2cXdBVTIyemMKLS0tIGlmUWJ4amN5Vk5ielMzUlZEcUJt
            aVp6VlI3QnduWkNiRzNMQUJIRmhkVFEKz18iiu751+PI8vfvMTi6md8oAM54TZLw
            owLIQINtC+6S13cvq6vnVJ44vETwlhnlXtZU9mqM5O4Fhh+B8vOrHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T17:40:41Z"
    mac: ENC[AES256_GCM,data:VrBvIWyKA0t+0K2LcIuiGPN/oO3WGNYxlMf6dBgJ/A9TodieTVTDnGZQ0zpIYamlH2zeiroA54qFEWFBZwvkgVfzw/Dn0E2Ds+LuGRv0/j3wpOkk9c5qbZrhTN+kjwgTb0PrhoGgehK1kz3zh0hV4XcE+demNqlIiRuLrLZTPLk=,iv:PIbc4dRLusjs4dI7jkEK7Dqan475A1i2Ewlu6OyLAg0=,tag:DSR5Z3J7361w4f3AlQaKZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
