apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  chart:
    spec:
      chart: pgo
      version: 5.X.X
      sourceRef:
        kind: HelmRepository
        name: pgo
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: postgres-operator

  values: #  helm show values oci://registry.developers.crunchydata.com/crunchydata/pgo | less
