apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastenhealth-db
  namespace: fastenhealth
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
