apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gotify
  namespace: flux-system
spec:
  interval: 15m
  path: flux/apps/gotify
  prune: true
  timeout: 2m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: gotify
      namespace: gotify
