apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ntfy
  namespace: flux-system
spec:
  interval: 15m
  path: flux/apps/ntfy
  prune: true
  timeout: 5m
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ntfy
      namespace: ntfy
