apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
  namespace: flux-system
spec:
  interval: 15m
  path: flux/apps/syncthing
  prune: true
  timeout: 2m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: syncthing
      namespace: syncthing
