apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptimekuma
  namespace: flux-system
spec:
  interval: 15m
  path: flux/apps/uptimekuma
  prune: true
  timeout: 2m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: uptimekuma
      namespace: uptimekuma
