apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin-operator
  namespace: flux-system
spec:
  interval: 15m
  path: flux/infra/intel-device-plugin-operator
  prune: true
  timeout: 2m0s
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: device-plugin-operator
      namespace: intel
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gpu-device-plugin
      namespace: intel
