apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 15m
  path: flux/infra/node-feature-discovery
  prune: true
  timeout: 2m0s
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: node-feature-discovery
      namespace: node-feature-discovery
