apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  interval: 15m
  path: flux/infra/prometheus-operator
  prune: true
  timeout: 2m0s
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: prometheus-operator
      namespace: prometheus-operator
