apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: navidrome
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
