apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  namespace: navidrome
  annotations:
    nfs.io/storage-path: "media/music"
spec:
  storageClassName: qnap-fixed-name-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
