apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plcbundle
  namespace: plcbundle
  annotations:
    nfs.io/storage-path: "plcbundle"
spec:
  storageClassName: qnap-fixed-name-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
