apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grampsweb-db
  namespace: grampsweb
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
