apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - custom-templates-pvc.yml
  - data-pvc.yml
  - dnsendpoint.yml
  - server-deployment.yml
  - service.yml
  - worker-deployment.yml
