apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-worker
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        readOnlyRootFilesystem: true
      containers:
        - name: authentik-worker
          image: ghcr.io/goauthentik/server:2026.8.1
          args:
            - worker
          envFrom:
            - secretRef:
                name: authentik-secrets
          env:
            - name: TZ
              value: "America/Puerto_Rico"
          podSecurityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "Always"
          ports:
            - name: authentik-http
              containerPort: 9000
              protocol: TCP
            - name: authentik-https
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: authentik-data
            - mountPath: /templates
              name: authentik-custom-templates
          # livenessProbe:
          #   tcpSocket:
          #     port: authentik-http
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: authentik-http
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          resources:
            requests:
              memory: "512M"
              cpu: ".5"
            limits:
              memory: "1G"
              cpu: "1"

      volumes:
        - name: authentik-data
          persistentVolumeClaim:
            claimName: authentik-data
        - name: authentik-custom-templates
          persistentVolumeClaim:
            claimName: authentik-custom-templates
