apiVersion: v1
kind: Service
metadata:
  name: cinny
  namespace: cinny
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cinny
  ports:
    - name: cinny
      port: 8080
      targetPort: cinny
      protocol: TCP
