---
# This ConfigMap is just a way to define the cloudflared config.yaml file in k8s.
# It's useful to define it in k8s, rather than as a stand-alone .yaml file, because
# this lets you use various k8s templating solutions (e.g. Helm charts) to
# parameterize your config, instead of just using string literals.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: tartarus-home
    credentials-file: /etc/cloudflared/creds/credentials.json
    loglevel: warn

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: mealie.tartarus.us
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        httpHostHeader: "mealie.tartarus.us"

    - hostname: bsky.tartarus.us
      service: http://bsky.bsky.svc.cluster.local:6767
      originRequest:
        httpHostHeader: "bsky.tartarus.us"

    - hostname: knot.tartarus.us
      service: http://knot-web.knot.svc.cluster.local:5555
      originRequest:
        httpHostHeader: "knot.tartarus.us"

    - hostname: irc.tartarus.us
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        httpHostHeader: "irc.tartarus.us"

    - hostname: heimdall.tartarus.us
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        httpHostHeader: "heimdall.tartarus.us"

    - hostname: dashy.tartarus.us
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        httpHostHeader: "dashy.tartarus.us"

    - hostname: gotify.tartarus.us
      service: https://traefik.traefik.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
        httpHostHeader: "gotify.tartarus.us"

    - hostname: uptimekuma.tartarus.us
      service: http://uptimekuma.uptimekuma.svc.cluster.local:3001
      originRequest:
        httpHostHeader: "uptimekuma.tartarus.us"
        
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
