---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudflared

  template:
    metadata:
      labels:
        app: cloudflared

    spec:
      automountServiceAccountToken: false

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: cloudflared
              topologyKey: kubernetes.io/hostname

      securityContext:
        fsGroup: 20000
        fsGroupChangePolicy: "Always"
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: cloudflared
          image: docker.io/cloudflare/cloudflared:2026.8.3
          imagePullPolicy: IfNotPresent
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run

          securityContext:
            runAsUser: 20000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - NET_RAW

          livenessProbe:
            tcpSocket:
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true

      volumes:
        - name: creds
          secret:
            secretName: cloudflare-tunnel-json
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
