apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw-operator
resources:
  - gog-config-pvc.yml
  - https-redirect-middleware.yml
  - ingressroute.yaml
  - openclaw-agent.yml
  - reflect-prod-cert.yml
  - syncthing-pvc.yml
configMapGenerator:
  - name: openclaw-agent-config
    files:
      - files/openclaw.json
generatorOptions:
  disableNameSuffixHash: true
