apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minetest-data
  namespace: minetest
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
