apiVersion: apps/v1
kind: Deployment
metadata:
  name: minetest
  namespace: minetest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minetest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minetest
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        readOnlyRootFilesystem: true
      containers:
        - name: minetest
          image: linuxserver/luanti:5.14.0
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "2000"
            - name: PGID
              value: "2000"
            - name: CLI_ARGS
              value: "--config /configmaps/minetest.conf --gameid voxelibre"
          podSecurityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "Always"
          ports:
            - name: minetest
              containerPort: 30000
              protocol: UDP
          volumeMounts:
            - mountPath: /config/.minetest
              name: minetest-data
            - name: minetest-configmap
              mountPath: /configmaps
              # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: minetest
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: minetest
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "1G"
              cpu: "1"

      volumes:
        - name: minetest-data
          persistentVolumeClaim:
            claimName: minetest-data
        - name: minetest-configmap
          configMap:
            name: minetest-configmap
