---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minetest
resources:
  - ./data-pvc.yml
  - ./deployment.yml
  - ./service.yml
configMapGenerator:
  - name: minetest-configmap
    files:
      - minetest.conf
