apiVersion: v1
kind: Service
metadata:
  name: minetest
  namespace: minetest
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minetest
  ports:
    - name: minetest
      port: 30000
      targetPort: minetest
      protocol: UDP
