apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cloudnative-pg
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    config:
      # -- This option determines if the operator is responsible for observing
      # events across the entire Kubernetes cluster or if its focus should be
      # narrowed down to the specific namespace within which it has been deployed.
      clusterWide: false
