apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: telegraf-ds
  name: telegraf-ds-role
rules:
  - apiGroups: [""]
    resources:
      - deployments
      - services
      - pods
      - nodes
      - statefulsets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telegraf-ds-rolebinding
  namespace: telegraf-ds
subjects:
  - kind: ServiceAccount
    name: telegraf-ds
    namespace: telegraf-ds
roleRef:
  kind: Role
  name: telegraf-ds-role
  apiGroup: rbac.authorization.k8s.io
