apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  namespace: wordpress
  annotations:
    nfs.io/storage-path: "media"
spec:
  storageClassName: qnap-fixed-name-nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
