---
# vars file for common
common_users:
  - name: benjamin
    pub_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLPeoF1/3ixnmeznZaofmspWcgGhz+5f7byDqC3hgaLEczQGE/b6yEaKf0yPbjM5aCn8Y7mpBvxPFyIJCbf4F7rnh/3PzWc4e1qdxiDnds46Cj7QXFrS6poy6UwUJcis+nJwolGYsssTUTv7ZQxGDzo2SHfW/3MmSLhjUe70dgjvb21Vx/I+neyM00BqSwxzyt4wxT03HBdyKu2Z69ATDrP+cWN8+qpu015FxutIeWBJzJya2Sx8ckL/VTncbn3f6bSE0WUHPY2yQy15ct93HMw/sMUxbxpq1YVLeARYWtHnC25gJy5hmKYLLVhDdPBPy1Rw1FeTTM4ABe01sGB3aWB6PmZ3tyIBY/cQ496mVZliRzE3WvJ43kKok1j9UMlvdQHw6eovmNl+g1pmL1/iDSO7fJto+aSXluM4fXCtjekLjpmt9WW1bGAoP/gkWZg62SbixjHYU6ABlnxxLNisY8J7mu8sDirQWDy988HR3GaRu+LAzlZe7eEhk1LSqIe8qRd4pdEW2Hy3dz/SB75TJ1/ttI7Z1Ovcnefdj9odPgQ15f3SsvE/YtCjwg/T75HTUe9hVYCFuNbcPi3U45QYhNOf1jBt3NVP2bPHTYTgrOptj+xdLGTOGQkI2cMqIcSNwG0m03KfyLxlHVavRkjynvTf649uYma4HJPxyFSaJFyw== blbecker@phobos"
