# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  backend "s3" {
    region  = "us-east-2"
    bucket  = "tartarus-infra"
    key     = "terraform/top_of_rack/terraform.tfstate"
    encrypt = true
  }
}
