apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 6.X.X
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-api-token
      proxied: false
    crd:
      create: true
    sources:
      - crd
      - traefik-proxy
