apiVersion: v1
kind: ConfigMap
metadata:
  name: continuwuity-configmap
  namespace: continuwuity
data:
  CONTINUWUITY_SERVER_NAME: bckr.me
  CONTINUWUITY_DATABASE_PATH: /data/db
  CONTINUWUITY_PORT: "6167"
  CONTINUWUITY_MAX_REQUEST_SIZE: "20000000" # in bytes, ~20 MB
  CONTINUWUITY_ALLOW_REGISTRATION: "true"
  CONTINUWUITY_ALLOW_FEDERATION: "true"
  CONTINUWUITY_ALLOW_CHECK_FOR_UPDATES: "true"
  CONTINUWUITY_TRUSTED_SERVERS: '["matrix.org","matrixrooms.info"]'
  CONTINUWUITY_ADDRESS: 0.0.0.0
  CONTINUWUITY_ROCKSDB_PARALLELISM_THREADS: "1"
  CONTINUWUITY_DATABASE_BACKEND: "rocksdb"
