apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsky-data
  namespace: bsky
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
