apiVersion: v1
kind: ConfigMap
metadata:
  name: bsky-configmap
  namespace: bsky
data:
  PDS_HOSTNAME: bsky.tartarus.us #bluesky.yourdomain.com
  PDS_EMAIL_FROM_ADDRESS: admin@bsky.tartarus.us #admin@domain.com
  PDS_MODERATION_EMAIL_ADDRESS: admin@bsky.tartarus.us #admin@domain.com
  PDS_DATA_DIRECTORY: /pds
  PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
  PDS_BLOB_UPLOAD_LIMIT: "52428800"
  PDS_DID_PLC_URL: https://plc.directory
  PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
  PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
  PDS_REPORT_SERVICE_URL: https://mod.bsky.app
  PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
  PDS_CRAWLERS: https://bsky.network
  LOG_ENABLED: "false"
