apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config
  namespace: mealie
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
