apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        readOnlyRootFilesystem: true
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC2
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "2000"
            - name: PGID
              value: "2000"
            - name: ALLOW_SIGNUP
              value: "false"
            - name: BASE_URL
              value: https://mealie.tartarus.us
            - name: MAX_WORKERS
              value: "1"
          podSecurityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "Always"
          ports:
            - name: mealie
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: mealie-config
          livenessProbe:
            httpGet:
              path: /
              port: mealie
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: mealie
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "250M"
              cpu: ".25"
            limits:
              memory: "1G"
              cpu: "1"

      volumes:
        - name: mealie-config
          persistentVolumeClaim:
            claimName: mealie-config
