apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-config
  namespace: uptimekuma
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
