apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: tls-upstream
  namespace: harbor
spec:
  targetRefs:
    - kind: Service
      name: harbor
      group: ""
  validation:
    wellKnownCACertificates: "System"
    hostname: harbor.tartarus.us
