apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      version: 1.X.X
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: harbor
  values:
    externalURL: https://harbor.tartarus.us
    expose:
      type: clusterIP
      tls:
        certSource: auto
        auto:
          commonName: harbor.tartarus.us
    existingSecretAdminPassword: harbor
    existingSecretAdminPasswordKey: adminPassword
    database:
      type: external
      external:
        host: main-rw.cloudnative-pg.svc.cluster.local
        port: 5432
        username: harbor
        coreDatabase: harbor
        existingSecret: harbor
      # database.external.sslmode:
    redis:
      type: external
      external:
        addr: redis-master.redis.svc.cluster.local
        # sentinelMasterSet: The name of the set of Redis instances to monitor
        # coreDatabaseIndex: The database index for core 	0
        # jobserviceDatabaseIndex: The database index for jobservice 	1
        # registryDatabaseIndex: The database index for registry 	2
        # trivyAdapterIndex: The database index for trivy adapter 	5
        # harborDatabaseIndex: The database index for harbor miscellaneous business logic 	0
        # cacheLayerDatabaseIndex:
    persistence:
      enabled: Enable the data persistence or not 	true
      # resourcePolicy: Setting it to keep to avoid removing PVCs during a helm delete operation. Leaving it empty will delete PVCs after the chart deleted. Does not affect PVCs created for internal database and redis components. 	keep
      imageChartStorage:
        type: filesystem
      persistentVolumeClaim:
        trivy:
          existingClaim: harbor-data
          subPath: trivy/
        registry:
          existingClaim: harbor-data
          subPath: registry/
        jobservice:
          jobLog:
            existingClaim: harbor-data
            subPath: jobservice/
