apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knot-keys
  namespace: knot
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
