apiVersion: v1
kind: Service
metadata:
  name: knot-web
  namespace: knot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: knot
  ports:
    - name: knot-web
      port: 5555
      targetPort: knot-web
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: knot-ssh
  namespace: knot
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.40.72
  selector:
    app.kubernetes.io/name: knot
  ports:
    - name: knot-ssh
      port: 22
      targetPort: knot-ssh
      protocol: TCP
