---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-middleware
  namespace: openclaw-agent-dot
spec:
  redirectScheme:
    scheme: https
    permanent: true
