apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: calibre
  namespace: flux-system
spec:
  interval: 15m
  path: flux/apps/calibre
  prune: true # remove any elements later removed from the above path
  timeout: 2m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: calibre
      namespace: calibre
    - apiVersion: apps/v1
      kind: Deployment
      name: calibre-web
      namespace: calibre
