apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-private
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/clusters/tartarus.us
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-private
  commonMetadata:
    labels:
      repo: homelab-private
