apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 15m
  path: flux/infra/reflector
  prune: true # remove any elements later removed from the above path
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: server
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: reflector
      namespace: reflector
