apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-data
  namespace: backrest
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
