apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: backrest
  annotations:
    nfs.io/storage-path: "immich-photos"
spec:
  storageClassName: qnap-fixed-name-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
