apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw-operator
resources:
  - ./openclaw-agent.yml
configMapGenerator:
  - name: openclaw-agent-config
    files:
      - openclaw.json
generatorOptions:
  disableNameSuffixHash: true
