apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-agent-config
  namespace: openclaw-operator
data:
  openclaw.json: |
    {
      plugins: {
        enabled: true,
        allow: ["matrix"],
      }, 
      channels: {
        matrix: {
          enabled: true,
          homeserver: "https://continuwuity.tartarus.us",
          accessToken: "${MATRIX_ACCESS_TOKEN}",
          dm: { allowFrom: ["@benjamin:bckr.me"] },
          groupPolicy: "allowlist",
          encryption: true,
          groups: {
            "!general:bckr.me": {allow: true},
          },
          groupAllowFrom: ["@benjamin:bckr.me"],
        },
      },
      agents: {
        defaults: {
          model: {
            primary: "openrouter/deepseek/deepseek-v3.2"
          },
          models: {
            "openrouter/deepseek/deepseek-v3.2": {}
          }
        }
      }
    }
