apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge-config
  namespace: thelounge
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
