apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.X.X
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: node-feature-discovery
  values:
