apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-private
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com:22/blbecker/homelab-private.git # ssh://user@example.com:22/repository.git
  ref:
    branch: main
  secretRef:
    name: homelab-private-deploy-key
