---
- name: Restart k3s on all cluster nodes
  hosts:
    - k3s_servers
    - k3s_agents
  become: true
  serial: 1

  tasks:
    - name: Restart k3s server service
      ansible.builtin.systemd:
        name: k3s
        state: restarted
      when: "'k3s_servers' in group_names"

    - name: Restart k3s agent service
      ansible.builtin.systemd:
        name: k3s-agent
        state: restarted
      when: "'k3s_agents' in group_names"
