apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tranquil-pds
resources:
  - blobs-pvc.yaml
  - deployment.yaml
  - dnsendpoint.yaml
  - service.yaml
  - store-pvc.yaml
configMapGenerator:
  - name: tranquil-pds-config
    files:
      - files/config.toml
