apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranquil-pds-store
  annotations:
    nfs.io/storage-path: "tranquil-pds/store"
spec:
  storageClassName: qnap-fixed-name-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
