apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: redis
  values: # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
    architecture: replication
