apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik.tartarus.us"
spec:
  gatewayClassName: traefik

  listeners:
    - name: web
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All

    - name: websecure
      port: 8443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: letsencrypt-wildcard-cert-tartarus.us-prod
      allowedRoutes:
        namespaces:
          from: All
