apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 23.X.X
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: traefik
  values: # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    tlsStore:
      default:
        defaultCertificate:
          secretName: letsencrypt-wildcard-cert-tartarus.us-prod
    logs:
      general:
        level: DEBUG
      access:
        enabled: true

    additionalArguments:
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.forwardedHeaders.trustedIPs=10.0.0.0/8"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8"

    service:
      loadBalancerIP: 192.168.40.84

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.tartarus.us`)
        entryPoints: ["websecure"]
        tls:
          secretName: letsencrypt-wildcard-cert-tartarus.us-prod
