apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main
  namespace: cloudnative-pg
spec:
  instances: 3

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  postgresql:
    shared_preload_libraries: # load vchord shared library
      - "vchord"

  storage:
    storageClass: longhorn-no-replication
    size: 5Gi

  walStorage:
    storageClass: longhorn-no-replication
    size: 3Gi

  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  managed:
    roles:
      - name: gotify
        ensure: present
        comment: Gotify notification server
        login: true
        superuser: false
        passwordSecret:
          name: gotify-pg-user-creds

      - name: harbor
        ensure: present
        comment: Harbor
        login: true
        superuser: false
        passwordSecret:
          name: harbor-pg-user-creds

      - name: ntfy
        ensure: present
        comment: ntfy.sh notification server
        login: true
        superuser: false
        passwordSecret:
          name: ntfy-pg-user-creds

      - name: immich
        ensure: present
        comment: immich photo server
        login: true
        superuser: true
        passwordSecret:
          name: immich-pg-user-creds
