apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      securityContext:
        readOnlyRootFilesystem: true
      containers:
        - name: bazarr
          image: linuxserver/bazarr:1.5.3
          env:
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "2000"
            - name: PGID
              value: "2000"
          podSecurityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "Always"
          ports:
            - name: bazarr
              containerPort: 6767
              protocol: TCP

          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: /data
              name: bazarr-media
            - mountPath: /tmp
              name: temp
          livenessProbe:
            tcpSocket:
              port: bazarr
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: bazarr
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "250M"
              cpu: ".5"
            limits:
              memory: "2G"
              cpu: "2"
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: bazarr-media
          persistentVolumeClaim:
            claimName: bazarr-media-qnap
        - name: temp
          emptyDir:
            sizeLimit: 100Mi
