base-url: https://ntfy.tartarus.us
attachment-cache-dir: "/var/cache/ntfy/attachments"
behind-proxy: true
auth-default-access: "deny-all"
auth-access:
  - "*:up*:wo"
  - "uptimekuma:uptimekuma:wo"
  - "openclaw:openclaw:wo"
  - "apprise:apprise:wo"
