apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: atcr-registry
  namespace: knot
data:
  .dockerconfigjson: ENC[AES256_GCM,data:fiZVlmwnhN9gC2MhJbsbBDMqk6+rNrjJYBHRE/k8+bHdSDsKovJgVQ7zyBsyEpfdwwATI8eZlMs5UMlEF7vihoiSdpmtn+xSr9D4qTRdib3Mu+4aUCQOHDCUXOL28oG1ZC9q1a9r1kaPMLmt2gsvAhmuoRWDxvv16AQYSb+P9bI73qrpWcr4hYEPMD8asN5X0AmYUFE7UdZ/3usn3Rug4QRNWYY4BxOEJJL7wn6H5+qFjIIUmdyLwdsWQAr1NNeFck92Puj3K6iXTt7iUU2OcgH8jiF8a6MTAVQtpRUlfPvTBdROSoryLg==,iv:OLRDVBXE63KRnWlXSdPeNT10Do3GJykPUjtcIG2OEeY=,tag:4m4TNm3lMwQVNiAYsCO6sg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ2FUZGViOWhrYlp6cThj
        SHREZGxxSE5JdkpaUlI3MnJIVVlMY1d5dmtrCjhRV3d2M3JZMTdteEE0eVJ6Rldo
        Vk05V05tN0w1Z1R4VEFySDlIVVFBelUKLS0tIE5JZ3pCcmlLbzYrbUFhZEV4Rldq
        SDFOSnhKVERBQkhlY2lVMk55aHd4WkkK6eMlicrEHAX6S7mOuIoWSGDPafKZGtmk
        W+yaBn5+fOaqqgEggIk6PLgDbs8dlt3iXJ+zp3JonfaEneGLN5siGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-13T13:31:31Z"
  mac: ENC[AES256_GCM,data:3ESpp8QIE+sZjn8/P4Js/fGnsu5I42p25KWMKErlQW/UVhlYR2eYPbYXlUgZCeUOAACfQK4aaY/StP9oW64Mvb5QakzcENRgjSIfum+zIAlI0ZRS2HqfQxJ92HtTIl+rVzFKKCtbxRBQnIK0QSd+5VykVzGILXPq+y8BFjkGhGs=,iv:WCsXfyJTgZYPGKw+E/SFG1/OEMezkvSO6qn7ekjA6WM=,tag:wRu0+P6eI4H3kphb44DLhg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
