apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: atcr-registry
    namespace: knot
data:
    .dockerconfigjson: ENC[AES256_GCM,data:2NEbisOi+E7djDXbXA780WVYBquHYJSbgJtuSOqbsGA8P72ljv3qHMQlijMEzmLMc3wF5FcbqEXdaLrQOdm2EOlYD/y6DoNPm0pvacdef/jeFPU4NlONZ+/o7gP/8ABzkUiRblkAxRF5o1D6fx1eTGD+20EaYYLb79saIKDFHBXTfk562yAUntXY1ACPxcrpAHyhdP23d+yk0P11KjFXp3WxBbjYv2KmQ7xlTWQEvTurM98dMmTxu6BlVfZcFgohfDeTx6rnBkVG6wFf/Qu0hPvj5PK3rQiZZFc306UHkFsg6uNdy/wJ4Q==,iv:gX2VctMag0sr5+U46JqcOELIpBY9vuRPrvxLKuTId70=,tag:gsqLPKYIa3M7OhEUKYS79w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M2pobWtvU3VQV3ZCTW9k
            YXBDNi9zc1V0Rkt0YUNPY3Jzc0pSMWUrVndvCnBmZXpSWlFGQjNnV0IzZzgwemVY
            ZjVxbnlLWi9mVWpJVWN3YXorajcxT3cKLS0tIG0rV3N6ZXJaUUhOMTljc1pmY3h2
            L202T1A1dlJLMjhLYUVpYVNMUG1rZTgKxw/WY48geZqNijp+oBJDwP9tV/2EtKZa
            oiywnIvyUv6SW0CuH/lH5O8PFSMXpKkDDkCFMsp1FxuTI9xggDlPiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T19:29:01Z"
    mac: ENC[AES256_GCM,data:6lYgc/BH8J6VkhilBwxobVoqd58zyL70GzSI5XeYtZ+DIoxR41tITnHDXBS++MU0RqPncSbUOXaju89gnPHRmyAFgOdgXuNSe/3Z+/y0jh/1e6fmXaEWvqmfIZEWQR/cFURd1Oc6VShjXoaKdTtPDhbrgTSvC1LDkteQrXK0o10=,iv:k71uuicsApnVy146GQCrUoaQXiCT2BUPOdj1BxkG6Vg=,tag:mR/syxWdJxsT3mTPc19d+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
