apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:0UTqAR4YXBuJEvoAEzjEg7d58D2ud+guu0b56H7+LixBCUIT2dbSrw==,iv:wg2M/Mis9v8Bf4AhRrzzvM1skFhgQXobAkXhnPXBaNs=,tag:xuGVJVCECYY4TZGEPk9EzA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:90DUKfLqxaTe,iv:nmmWYqBqbEh7vHFOxkw+4XQvDSjRo17Z6YiwfvNSZNY=,tag:PEDsPTdIvai06LcjZDpavA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:AdolYqBYlBxrOpTuWjrPCVBRUeuIs3u2ujOCNwTTMMs=,iv:cgVrKPfqpXDWLVotECBq9XcDVZSkFIofZ0agADPswPY=,tag:VW1OmX/k5AspPuc4kFy2Wg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:aysLwJwzZVFt6AVspQy6WUM6we5Tfp4LUz6HdGtc4n/f4/0Fn8ykgClUSAoBQQEzE9tlDUIh4719Fl2+cm6jV6MR+6MxmiWseBspEziyO5Q=,iv:s/Q0i/CrZv0zA93Xk4TrTANGhdqjz+VN7vx1ZaQlMSI=,tag:B4OKOde/9BXYxp22pb2EvQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVjN2cWQxV0RVVjYybnpo
            M0JvU3dRTFRGbnVtTSs2SUZOYjk2TlFpRjFJCklsdUpTNGRGN2RHcFhlY056dDg1
            NUJRaStJb2UwNHRqSlNvNFpFd0NkRFkKLS0tIEg0OGhuSEFqY3hwS1Mxc01mMHpG
            OHhxK2ZYNVFicjRsamxyMlB3N0l5U2MKdRFKMBldRiUWlrJ+D436W0US8iuVlfn+
            kRDdl8nci4w1YPd7IhQgi26cfBim7sQzt8GDgV5owlp7Blk6o9yckg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T03:48:35Z"
    mac: ENC[AES256_GCM,data:NL4Wk8MmTXu0uyoV9ob8i3tLlg6fxPGMidM+xWxZpBpe4l2fSs23DCd4wws5kd8DdM7fjM/9pAk0mdNWhR4th6Dw3O4XAXCIH3HghN6Q0uN/viK/1ZiKjtfDgW5zf/H2lNhRSPN8J5zjhZOE2udnrYMPNSHnz4SHf7hr6wXGvyE=,iv:Wlr/k5PBqONmm/ft13qnT0HP+0QxBorgHWQy/Xs20a4=,tag:1BjyMjnVNkD52fYcNH2irQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
