apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:dpZNS1xy6DkYwSc/pq3uReajXA30y0z+KBp0VOyPSBOh33cthvG3cQ==,iv:gCXbtY4f9CCmztgCWD+OnuW8cm6iTb3rRN7XVIoAGRo=,tag:z+AR/cgxGQhwJNMK9LjHrw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:JmHe8NLadzg7,iv:saW+AamfXyBV7FshwV2Gun1FOtJYVTxkVOYyDYdPflA=,tag:zD4XmhAES+eSXEiD8MlT5A==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Bq5+qvncNXw2K/C6APTT9WSIWfrSwfzU++SVtAXfX3A=,iv:ATc0BEajDUnoTkBUk5rffHYcQYIrLRdkcSvUaQPhimU=,tag:Es2R+lVqsZ/n/Kc4eUltSw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:PKFrO2HBuCypN95icFR7Hd4o5La3bZNRfV78fpz4UI0MRWMVdOdHlwiKhVFz7EEhTKhp1qnEj9KlIRqvfTOFHfWW3VGH+sed/l2DUkdi3pw=,iv:tjqZ6A7PiWMkKyHAs7wZ4TX+3jHPpuKszVdEXKhj77I=,tag:2gm5J8syUrlrF+mFaF/j4w==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:L/K4LEtibe+P,iv:d9h2Wch6O8WawtcQ/+gzawtUKtDF9gfm+ctrD7OoX58=,tag:ENiYDJTGQa3q5esuGVdDLQ==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:Iis=,iv:NKBbbnS82DScmY3Pw0DHrzOd4D6yZ8pbYhcDH3iA34s=,tag:wNovHpJ9+iMzNzlQ4xdzKg==,type:int]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:p2G4fAv8Kp/l9IeZ426pMqMXLle0,iv:lDP7uBvNNQMBlngr1JlMW6iFyS59Y5VsJJeoa7RNUco=,tag:Lzouay9wFkjums8wLhpTYQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:n5oPi2XsKPQM5rrWD8nn3Q==,iv:Y0bYCkaZEm+2M3MGCf9p+MSyIdH5j//Z4fcWHq5rEnA=,tag:4Y0AnGHXMwaJv7CYsgdaww==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:Xd+57Q==,iv:hViZBQeTHlOEkS+C/qvzgVc/4SD0bsEJhTO3XvuOzyo=,tag:9Gna1+qhcL+8/PFc9I/xYA==,type:bool]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:IGQ=,iv:sRo/p7VQOQw2wNEW9DvuZspG5cmQ7mxbCp8N3FU0xBs=,tag:GCkMmhOBHaljv4dORqHBuw==,type:int]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:Pg+NH528QerDfoI6VR1ymwg2/sSh,iv:/H61C7DWQ1x1lLJOIa2mI/Q/+JscmOu/29BegXtUsaE=,tag:2+6XzZO9KmCrKB6z2Rq2ag==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ckNXM3RhTUdmU0ZmU3d6
            aGhIV0UwYXpEUjVSM1VXcGNXWmJ6cmo5N0FzCi9OUXRhT0NkVktiUncwOWQwTXpT
            RzZMRkpoRGRCZDV2V0lnL3haQTlGRkUKLS0tIDVhMkV5MzAxR2p0Uzl4T1YxWTRs
            MnVuNmswOEdEVEE1YzRUSjc3aTdrTXMKQWsa+CnMXoZJ5Yn4KACDinqDCXJ4GTWC
            Bk7yxEvHSWnAJgYRmCDaEISMAZ5s5lizCGjbRSTLNyvwGEJv6IJG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T04:51:01Z"
    mac: ENC[AES256_GCM,data:gwmNoDafHYVLEFVDxzR6VWnpDp04gQaEU39eIkVApc5Y67RkumXWJ04NrAkMhA3PKvI2h9FYC80FeP6jhh/cygTJlaKH4egqS09AFOWoH2kqC+78yggQoIeqtdpVclTgVweGf8C5DvN3Twx8gxuoj0S5rFWAjl2Dx+D/cDJLyBc=,iv:4PePWbHCzYTMuyBnXdZsrpaoDCw8EoH3gklf3/22Dws=,tag:8GM5O+SMtqx5eHaHem+MJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
