apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:8oq2p7ylwWCGd+Zas+PrA9Vi+3niYlHHabINgs4PtWzwtNAZRxpEYA==,iv:NiM+YKJUArsxMEVkBtg2xjOrHKu1JqKhWxZHAkc0yZs=,tag:jZEZocqbE8L0lQPuDgleMA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:6MOtKMauuJ6h,iv:Bv+1UfN4ZG4YtqqDYQ9Wlh10ej0GC3piuArbEcUBl/Y=,tag:0/wiE44jFCClUavQErdi8Q==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:yhB+XZLWWImXyO7iimJWEdaH3X2Ni2MPxUe5hWM6CUc=,iv:Yf0uE+XkZZmYtK83Sasz7njLAiJR79Y5iPUTUpgHEf4=,tag:x8FxjiTuv0jHs+EbR0uNuw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:IBE9jzFpC6hgFyQPkij1aFabbcbBEP0yXMMPc9ft/lsWcxwc1dZMnyZnyuTwat3fdC8pRduzwXUexRo/eioG5PxPwFv0jvQEaTXIou5TGAY=,iv:k+FpW12Lfm/wysOlxrZ8FjGNUx0bN5+7L4XJf12KEXo=,tag:puqjQE8M21Es3lScwdgn/g==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:qxnYXjhc8sX5hu3FoQB2pw==,iv:z92RgERLBdroTeEunUM2eJ6D2l1Q0tE3uN3k0Os10O4=,tag:eC1BMjvM8pX0rw6VNbx/GA==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:LqGv,iv:OkoWkUILRrEYpbgxkuA6Z3n2iP6m/IyPQya/E2QEeJ8=,tag:v5XmdKnUqkwnAywdeMUTfw==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:98gaU/D5jkc8tORFnPhiN5QZ1CQO,iv:udiAD6gQ2mJthuipy65wY0P2krI7R7cJ17x71vyQMzg=,tag:xMHmzIgrfaKh/Kof2LW9GA==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:Hn2VTvoGJsP0zpZ1xqTEww==,iv:z5kE6EashAD7Bjd7hq8I1aOGurlisAfBPR1Cj9Ol6gs=,tag:2mjcfjb6cXOXTMFIcQdtaw==,type:str]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:Ia+ocA==,iv:tO4Wr9Iwki+H8Ko6rK2/UTBKRfvjhWGHf5/zlQzmKRo=,tag:MEet7nSgqC9cMzBUgPZVFw==,type:str]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:JQg=,iv:swnabTDw3gYQNxRuyr/9IxxU+LEvIZ/oQbXwpS++Vbk=,tag:XzF0m54z0TG0GiEuTtseyA==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:MULtz1MB9kEmNa50pfWwzglhRSBQhbTVPBWKh2GkVoBD,iv:3uEe2inJqmPwIJuYFx5PtVua7n2HFp2yb7ILeH+IjwQ=,tag:MbaonnMqdieaCvsdQx1x2A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTllUzFhT0oxY1FjdDI5
            N2FNSjJMK1pEV2ZEZm5GSnhrUHFMbnlZU1UwCmU5dlF3cXhCSjhZQnVnSzJRRStC
            REhBVHVzU1BFck5sTmlndmxpaklQb2sKLS0tIFE4NjNyc2JTdXdyM1pRaWx1bzBY
            K25jUnhiMXBsZHV4OVI5YzJ1VEhrTFkKLpi3ma6PngRuFO1LQ0u02oFTmw0fAL/P
            I5LpcHmboTPKTmLH7i6SNmBcaYhHhZuJOJSQLKUTLf2dBtrQy0YEJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T05:57:47Z"
    mac: ENC[AES256_GCM,data:BqdidQwMWWVP+0sWnnooLX5vWmket3le3D/A8GdrT221WD8opWw6M5iBoDy8imflAgRCgjI8DKJhbLhHaG3u+Mxy+LkJDXykw5llXPDYBLA3TMkoYbYySknkw/Vyrrkg/6b0EcJs+c+R76W7T+kfLuMchA4apeJ6mFmZOrH1aU8=,iv:IVjEsAGdf4l3204IvOwivfL8XVliLBIEN+h8XtQV4SM=,tag:Y0D3RaCxvMv3EFFIJSPK9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
