apiVersion: v1
kind: Secret
metadata:
  name: bsky-secrets
  namespace: bsky
stringData:
  PDS_JWT_SECRET: ENC[AES256_GCM,data:nQJhN74Vkne2OpLdBDotyqmlIPkvz8zrrrfzCn/JzRU=,iv:GdMP9qrqHaGCzqecVyxAWA8Lf8ol7/I5fCGHkaXHyRA=,tag:iemQM0lRmczoZ4iF8IXvSw==,type:str]
  PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:DfpEjz0nAWa2VjcNd5jFAL/DWA0plw6bX6r4CuJ7uUE=,iv:nS2nD2Dq/wLnQqx97L1Zs93VdA3GilxtGY9MO7SeO2Q=,tag:JMU1lAy2vjX0Yj58TypRUw==,type:str]
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:xWbwH6ZRVyX+udNcah2aLXse2+V+qIeeDRLkJH5sKybu4WtxFfeECu2oLyFnWszDV4GO7vtsWprTH8BTRZSAZg==,iv:poFbTjmnoKvPKqkCxMY5aWlZ/YUBb+I3pzAOx8jjX1U=,tag:5klYdSYG0E0N8fFjORSXUQ==,type:str]
  PDS_MODERATION_EMAIL_SMTP_URL: ENC[AES256_GCM,data:5F6EFjbgy2JPd4+ed/fyDJRzlS5Nrqngz5JSAuKMPpSs4uP8FtNf/TaJioFWnvfijMrdlA1QSj8f6Qf8Uw==,iv:b9oyB9oVen0E45/ccB9Qvsv3Bhun4d9QySL/W9zzom8=,tag:BnKIad7SFeHt6M1Fenq9JQ==,type:str]
  PDS_EMAIL_SMTP_URL: ENC[AES256_GCM,data:rObBl2SwGtpikVZ1sv9ahpmPm2WJcncFYfOdIRusNMl1ZRXUu+/D6BcFt3uVfn0vkyIOH/aZVA4TyZ+O1w==,iv:ssbu8GS9u2UYBDWZiotVC+gY+clxKh+O/AWGkA9vNj0=,tag:lcheJ3GPV2sw90ls4Ge8hw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeTJBeGtLTTd4bkp6MHdZ
        aHB5ZWJ5UVk5TGRwRUJPQXB4QXdOMTM1bmc0ClRucWxFdkUxTmo5Q0x3d0FvWjQx
        bVhGSlYrK1ExbzlneWFCbFFvckF0a0UKLS0tIEV0WjUzQWd2SE9rUFFGY3RPbzJT
        UmlVdTJBbFF6Q25LeXZRaFhuUGd1QlkKWHXPswb/rVWcM4S/2No1yOZuinnoiSAL
        8juQprIwYxZqHtLZhS4ofdDr5lv29wlGKYAqj9RJTbXA+J6Tk4VXVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-30T00:10:54Z"
  mac: ENC[AES256_GCM,data:DjBtVe3ipwawR/rPTaN2eAEt/zyuwGUbJL9XKHkOZX+hDbdBiGIl7wtAMnXOUC6GuZCwwz65dtMh/teFGidVo4FaohGm/GJ90y4sYgEwWo0OivRZNxQ8sI8LG8S/KvY/qf2iavM/F6jZcdqqLnwBeTItyoPqB9vOKhKkePj4S3w=,iv:2sY/2Zmd+CWM9fIOnnbo4UEnyYg1xsZnI5tQeDxjkEk=,tag:hxW4pQV/Y0fa61aXarj2Cg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
