apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:2yh7uWRMcV3H8Wg2wmPSjYiBzzyfoHouqrtO+3dNrl7RGe3YOYtA97z3cGlzWhaMSF4BVB8xnxA83ra3CgzfcPfyddfAN76nrS0ozKQzniOOIHvG2LsfhZFk8EcpMoXW/CPWOTbUrb+wmMzAUyZaS2appbxFRtR+x4ha2vBQ6or7HU8tWmfv39QDK4F9u+ktyCzO1bYczjOKX2e0QrbeWw8K1JU8uYLKX+Pv910KGoP9ypaSuegDpKzrGJFaj4eiVHGXoJuMXdlmxZtGfJqUUFIVp7ku5ux/,iv:MSdO9S9RIWgkqpB3WQ6KjuuaPfy7SzgieJx4JU3PBP0=,tag:JOkr40bL5R6fWnkbbboP3A==,type:str]
kind: Secret
metadata:
  name: cloudflare-tunnel-json
  namespace: cloudflared
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuczYvc3VjWWpPNjMrZTRq
        UmREdHJrZXlsckdrVW80N0dLenFXWDdVS3pBCjZnVUYyOUVuaWM5SVBIRForMWxh
        SE1qT0VsTmZHTlJzSjBORmZMalB5eUEKLS0tIHJ6STZ4UytrME41Wk51TjU4WnY2
        d1YvT1lkR0pyTFB3SGJEM25nM3labFkKX9e18GsSKf8T/JVuw7Gq2ULYLOcLuli1
        SwUpg3+89+nhDMJWCgoCwp0+Hlv34s4mUyy6rM4jhcI8RIW+TgT7yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-06-02T14:43:00Z"
  mac: ENC[AES256_GCM,data:IpOCbHoE9agIZ5AmvnziErQNd7DWNuQf8zVgKL1q7i1zaDN4iZB4TjZ0qEvR7Z9Kki5aC7B9+xM7q8CxptlDa4mXMEBZYBTj5GvHIE7FIB2UQ/RJup4Ouwdrb+B9Wj2SnT/Wwe9Rmh5vMTMSeyG6rdXb/g2mIpQZdkcutJucXjU=,iv:4Q9pVqqZRmpn2vKJCuxD3dY6Rw8EBLDnvfyBjtxWc10=,tag:u3lqCKa7wTviRxsmsY+tsw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
