apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cloudflare-ddns
data:
  api-token: ENC[AES256_GCM,data:3VknBbocNcptPLLMmTIwDYC57V3+CoTqm7Uq5gSvSYU5/yHz+cyiBQZ9ODlBav2gDpcnnMyIZW8=,iv:VPPV3r9zj4UOaqjCQrmEhFEx0WDzvCrFUr02HWosx/4=,tag:x6Y+L7oG3WnMnngrRjJqVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VFA2RUJFbUtOZ2Z3cnB5
        RnZuSjU0MWNpYkhJdlFNZzgydmpTc1ZKV0JJCmVBVEt4OWdWdzFid1JFL0E0Vnd3
        UnRvbk1Jc3BMM2tFSklIMWxTTHR1dFUKLS0tIDVyR2ExM2NPSWg1Z0pZS2lYM0Jm
        eVhNZzh4R2dwdEh1OER2eHJpd3Bxdm8KPqDIBv6hG42BARPb1HzrE5smK8wFt+qF
        +ZZ5qS3OTRpNxrxRq7qRnXA9JUNDl4GbW3O81hNsomjQmpA2ZfzYeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-05-28T00:12:00Z"
  mac: ENC[AES256_GCM,data:j0peuQauYcW+qN2tNEU+AbsQ2Gs5cbEgHqm8cWxOsOUVK/b+yDh3Jga8ruzIOUCaBf5EsDvtwGw79FZpooh/W8v/MsjvYYbklAgTLxe9yJdFVpocet6+otiQ/2rLZ95rayixx8fSmqjTXS/KJQTAzBguyFu90/WoPCVSarn7448=,iv:O4OEtylyyZbZwvKaYkV5S8O1M/JAfPfyFVENzQB88zA=,tag:KBPRrjuCUNTjT5koGNzC7g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
