apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
data:
  cloudflare_api_token: ENC[AES256_GCM,data:TbEgkuuQupYJjV1LFEe6rPc8k/Jl70268fbt6KPfee33mvZf+0+ySf6Xos6o07XvKxtRW7OReVg=,iv:ZNno9LxUIXlFZ+osH+JgDOzQKHOx56uoffI7S6pS6oU=,tag:iAyKqjORGJlg8Lhjq5lNtg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R1V4MlJiVk8ySGNpeGdR
        b3RSYXo1REswelFwSXR3bTMyOTlHdXpZc2tRCjdGbHhOYXQ5d3NyMjdGNWRjNmVR
        cGJsMUJNSDBjVy96NUIzRUtucmthU1kKLS0tIGtVclVFSXU1azgvSUZyOFVWU0RF
        TlVWNWhTVzA2cWRSZkRZOEQ0REdUdWMKvop6OA8j8aNfXXYX0iuGW3VZQNQrIK/G
        nCAcsDAXPJrw5fHVWT2bEQQFZCZlsL0peIqUfqAOUsvD0LrNatpaAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-05-21T16:56:57Z"
  mac: ENC[AES256_GCM,data:MKF7Vaxmwqw/+W5ZCUW+zEsXmsscUtkMZxpmbwwuh85TZrhNGg9k1Kdem5z1J5BUySa219i+tWoYD8UyeDZL3j/X7Ju/O8JCQ86UYPKcUX2LRalx9g3iR3MDKIyYgajJBfdqtdnMnevb7zQwjtANdNAdRQ0OIHLdazu0srOD9gM=,iv:W2CKBq7zmYoEVWyxxC9g44VYjrCiLQaPvU5JKokfXms=,tag:ZRIJX3YbP8/jSBjovS2E6Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
