apiVersion: v1
kind: Secret
metadata:
  name: continuwuity-secrets
  namespace: continuwuity
stringData:
  #ENC[AES256_GCM,data:vrrjEbssuYRS9NiKRa48snoELsiFg6ueP2GTCLoirn/QJ0BsPVy5yyek/zuEKFe8GbHohvJ0yz/R7bX6/MR9,iv:Z8abbe0+vXVjZw8bv4KheW2T917OfFZfxIqaU34MbTo=,tag:O4LD+o6U3cgyjze9Lh9Mcg==,type:comment]
  CONTINUWUITY_REGISTRATION_TOKEN: ENC[AES256_GCM,data:FI9yGtmLeMzVRj8S0J7Z/+UspSR5MF0dWTu3vCl9pcOsuhO+HsJaufGzpSXuAgpnka9/9ftzHvMoeLOEw3MTzQ==,iv:IOEDMb7O+Vg453lyjUw/QuWrewmDLrbjzk8tlRUZo4Y=,tag:8zkKLJJy5ZWH3FNbuaAJMg==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUnZxWjBZM3hObTVkRFNY
        QW9CUVJ5MHBCdGpFLzNxQnA3dGFKalpTblFZCndOemV3WDhmOVdUazRRNHRTbG84
        RVJyb3hTZE1KemdXQ1BhTGJMUExLMlkKLS0tIGxXWjBQR29UbTh2d0RSMXlyUTMw
        QTFmNVFoN3dOT0Q2Ry84RWdlNW9nOWcKZSI7YRSct5msWI3xwsmgLSoInK2Ikj97
        5XZXcuxGwpu5uGiGRTUhZdKK7fx/6OSJTQt5BWgtXFdkuIKY5VuS7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T04:00:25Z"
  mac: ENC[AES256_GCM,data:AvELWIoguT3MMvlY+9Y1qSct6D/eKdyd3d28L1PtprhaU200UZufO+9QNOkTuTwHGlWqFhmcY/MXzKKuypO3JJ86W5+FGxUK9EtM03lkmnDLOkpBuazx4KeznsedtDgI9PYy4rwRIEs86Kl43nTYr/G67w9/OY99L4oPmd6cmLU=,iv:tgVDGHxD62ngFVJRGiPmXRxBqpgTFw5+yutFwncutSg=,tag:mfN6F6bf5PlgKoOK0a6pfQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
