apiVersion: v1
kind: Secret
metadata:
  name: gotify-secrets
  namespace: gotify
stringData:
  GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: ENC[AES256_GCM,data:aKk=,iv:ZWyruKcHaXltDP6DiPQv0TtSvQkGjR7LWJx7iq60Dp8=,tag:6RRLfvWwPffdCIA1zxDERg==,type:str]
  GOTIFY_DATABASE_DIALECT: ENC[AES256_GCM,data:upt0MTukaNA=,iv:vvKpssFiZLb04gt8AF1zFcYJpezYx9qDq6vo/aM7Iq0=,tag:BXvQwTFtaP2Gy6G5L8YTEA==,type:str]
  GOTIFY_DATABASE_CONNECTION: ENC[AES256_GCM,data:uvik2XM+9d912uuw6F2VNe+FTLCg2Avhu3Pb77glO15tmhWoCQKyqqeUfiE5Z3nqg6Q2Q1zFQIAuxdlwDZwSFmAt6qpohQsE5wPgcJYINmnQqoJr0uhTCNUFkLobugtrEBE55MvoqB81EutA3iYj/J1Knw==,iv:Pa3SLvu9Y6w3Etr0d+hdzyjIc3PyhoTCm9gTj5HmGSk=,tag:JkzYuWbp9FKwu4jDPwaIkQ==,type:str]
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:jTYKq14=,iv:ynDylDwb0JEfhA/olvWKbD8qOQWWrDtDOvPBqxlHWZI=,tag:KqscozDpghVRdowvKYQ90g==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:2cdT98P3yhqNhkBBJ8x4V0yap6xS7Kii,iv:pUZLmDGwYi0rL/gJmJCB8R6k9lA0mAr7nKMqLtR5IhQ=,tag:Rtj3FiMY09Wy1L5TjgnbQQ==,type:str]
  GOTIFY_PASSSTRENGTH: ENC[AES256_GCM,data:6kY=,iv:18N7C1sKMiwUAa7N2BdN5xJlb4Buyu5afSgNAzWGt4w=,tag:e/5kS80wUBBmtaUmpe683A==,type:str]
  GOTIFY_UPLOADEDIMAGESDIR: ENC[AES256_GCM,data:C9RcDQF3ZCQxfVo=,iv:jADwMO8nXMbNkQBuEVpurfOaT4FI9vp+X5A0mcZGOyE=,tag:n0tBfyNPxKnXI0Ayz+kSiw==,type:str]
  GOTIFY_PLUGINSDIR: ENC[AES256_GCM,data:iIKpKVOdVu8w0xOd,iv:oUJ6MmcGbw89sgPzLcHVwTQOamKGXrZ0Lr8uvwOlZG0=,tag:xGFtbUM0o5J7trsdx6VM2A==,type:str]
  GOTIFY_REGISTRATION: ENC[AES256_GCM,data:F6hZgw8=,iv:MpIUFArWddy8HVReCqxaFmFZozQfZaj6fhg7pKH58GI=,tag:jVolH+qW+MTOmjY7zpgVlw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWEzVndkQ2oxWUNJWTJW
        N0R0QU9oZVg1WkdKa3BCbUh6ZlhtMWoxVUE0CmxsL3VYbDNHQWJFa0YxZlFNM2xv
        NGtWblJoQ29kbVBDeXFXM3hmdmo0c2sKLS0tIEx1M1pReFRKbW9uKzV3YlBYTDdT
        eXZIVU44TmxOVHJTVWh0cW0yY2JTaVEKYNEytFQxaXtJcaopsdIqMT5DwV3QoPqa
        yAR0bj03JiulUafE6OevpwGSXzdDt07zrcKRykzdyo06OH88upQNdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T13:39:52Z"
  mac: ENC[AES256_GCM,data:KD06700pCL7LjdDT2WhI7QrjH/gym5z9z5S2xUZqLXpZmitTiUF0d3II1UiZtJK6voEUwuZ0az+U6XxyghjSUPOgtHtbTKDtU8+MxFt1gKDsnoNfWAFLIJYx4Q+E1LuSF6ip890iyRa7cmCIGOyMLsOzAUHF5urCDqw0bJTnDtg=,iv:Wwi36+ik+t4ZCiiBpV9vSqop2U63dSR1M8YjLC2kvj0=,tag:cHT53uv3FQh8l7e1xlxIGw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
