apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: harbor
  labels:
    cnpg.io/reload: "true"
stringData:
  username: harbor
  password: eipaichah9Woo5coh6SaibeizizeiCha
  adminPassword: Eeb5oaDeigh4Isao3doeT2xeeNgookuY
