apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: harbor
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:9Uf3ZH6X,iv:NjSLBzUKo2jt121W7CnwF+oAHhnfCKmMHfZrId79WVU=,tag:ZU3cWyM+8V1h7fBTDo9OYQ==,type:str]
  password: ENC[AES256_GCM,data:AHlDOv7lItQKFDiAZmR8MxJJdq35efogF0TMWEeeYXw=,iv:fzFQz2zJwMBYFD2+hR5WbanqMXpu0+P/0UgX3XbUW0E=,tag:o3hHb7DM9J03sL975jjdZg==,type:str]
  adminPassword: ENC[AES256_GCM,data:giY//PotXV6ILHGWWpA/Z2N8f44bEntWT33WfvZDpQc=,iv:kUZFnSFk3ju606LrflrzYBddQ8w0OhfkchET1GKaJ1E=,tag:WYkLzFVynZ1wC3iCTRMtbQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN3hDcjdDaEM5aFB2TkV6
        azhrcVNxVi9GVCtTU2dEbkQxd1hKbkg2VW1FCnVybm9QaHVtUVYwUmd6T1V5bTFT
        TVh3ZU5NZEhKU2h0Y1lzNm5pRjV0bkUKLS0tIEtDankrUEU5ajd1M09xNUxwUDZy
        KytuRitNTFVvWnNzR0dyUWk4cWxhdEkKk72xBBO7RfVTsLB5he24d0fWNr662+hp
        0cD5cDmXkCEKVo2UBkPwnwQVjOijb7NkxF37ToGN1ziSQ/AGXHNiRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T16:52:46Z"
  mac: ENC[AES256_GCM,data:y9owNjX4xVD8NKuHrPjoiHmsqrwb/cub/eMcwVWRgzY/Od677jImgG8kuKrjlGo8S3LcUNyi5mi1WSXIWWwwoCMGxkU9Di6VbcII54CrnHOhmESkTGICGMaGEXbVEga7Y/z7FJOBIKRUplyQmTyERC2iwsKSApHtwKssLOr7VP0=,iv:+f7ZU3Lv85oqytGpemuyATagXP3aSD9pgRXg/VJilmY=,tag:S2sMte44uGBjkOuHoJUnQA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
