apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: harbor
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:b6QTzEcf,iv:/DS2sAWDpjfYpT+ULDHmDA7mZKtxbOi9T8zLAQUCD5I=,tag:d0VDjuaU/CDgglGMHiJHiw==,type:str]
  password: ENC[AES256_GCM,data:oJB4i0pxitXpUJE0xmG9U/03JCMUBKLJ1kEUadKu1Mg=,iv:Zc78ZAFj/kNgeAV1xUeG6GQeTQcUIr/Knsu0ydbXlvE=,tag:Nq9u0u9AdlBLgS54c9Nu9A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIalh6cVYvaTRRUWtxN3I1
        Q3V6cm4yZ3o1Zmx5RkNwSjFtOW8yeUk1K200CjRzV0xUeGZMQTJRRXJqWFhsUERV
        eXBWMXMvY1I3NE9XK3ZvMkNzdmFiV28KLS0tIHd1aFJMNEtOUEZDTUZ4YzNzVUdB
        OXJ2Yk5CK0F4d0hRK0NQQitFSW0wZ2cKGFcf04qL+lruetIXUvolvt6u//LYTdw+
        QrwXmQcX0HffXnju7928UsfG/lQ07Mw1lULbe9i5798i2tuw1hlVeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T16:38:22Z"
  mac: ENC[AES256_GCM,data:3WFq696441HfOdQgZDo439lSh9kz2549SQpT7TLhLvGrYMNxtZge0Rpra0UFMxlpOBY7E1XZgI6Dt1txNVI/jlctwioP63lKXOWJ5EwZNz46nWwq3GltT4ppkrkH/ldNIhmwrJPWtEbM399OQ+u1dmizELYLgZTVzTe9bVBFksw=,iv:apAtSjLmdaY8a3n0NyB3QaFZMl42N3Be+BmZYEV3kTk=,tag:W1Zs5nntImqXMJMp1huqWQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
