apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:4f8wX2kf,iv:nvvntyV2VqXoxdQ0gfq1PrFgmXXlikDT9b1oLnFn4dQ=,tag:+gN3n0hGM5QfeGmWI2XJuA==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:Mjl3oipD,iv:0YbBMw8rnNFcUWtcBfLxueQ71iiJI44gcd9PET41Sw8=,tag:qaThlSOBhZrY7dAw36pMEQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:VfDlKeihalL59rqKRSdxGdpLGINEHWZ9,iv:V2rUZOefkuN9bs3GCOfUY0XlFS7d0iFd8NJOqx1pcxk=,tag:6ZN4xZisEz/5aJa6cF2wQw==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:67aO2VGv0ytpu6E85bIDB8K01zXv50mFD2e5UG9p7NINTH/Wa9CJXA==,iv:lo74QAhGc0R8D12btHvgDeHLpFy0GWXnk14N1ER1PAQ=,tag:1zb9TznZiVxKFJO9viYGLw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:rZC3nQ==,iv:koqkO7JfbbuWrd3R3Obo/MXg1ZA2wfklQ2+TedvdgA4=,tag:s7tN7+5WDHi1993Gc9U10Q==,type:int]
  REDIS_HOSTNAME: ENC[AES256_GCM,data:0fNFcmdH/c+py609ggrtRPO3ie/PgRMUzpcqGWK0YjmoRG0h,iv:ILo/4e8SmL5TU3Io22w3zzDvxjaL4a7FDuTW2JG04Cw=,tag:QX/HipNeTqBuc3kEP74CDw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV1o4Q3I3OTFnejFsUUxq
        MERRTmtFSFhZOFZ0MDVCZEpoc1h1QTdiT3dvCjlMUWlqZjRVV2QydHRpQ1FJL1RZ
        MjRXd1pXT2NJRVpjcEY2NVRjLzlLRlkKLS0tIDl0cklIN0w1d3B6VnBsQW5LYUZY
        ckNjQWFRWTR6RzhyV2Z1QktWVktpZzgKAny8Jyewgn2T2kVfjo/eReR6GcV3zNq9
        SM5VdEPoqYWGbCUTMDxsdvx0HNItD2phIHPj6U8UJG/lG/9px7GJFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T17:30:07Z"
  mac: ENC[AES256_GCM,data:YHaiSixN5OJekEh6eTvPmZXE59W5lOGstp0xWypSU8I2yITNJ7/rhrVQ1CaSuef3reoLnyCXVCPmkZvWC6b5ddl30KFEClvEGifdNmaYev3WbxvDpfb+lq7CSaYFsIwBrBJTBlhO2cbqrapCN3BIn+1fAidwzvmAKF5gDJiofrI=,iv:Y5IlQHMV/Pnx+a+/V//1LER0/juP7C0L716OeyTVakI=,tag:lzsCuht0w4y0Kx3fKUwORA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
