apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:IZAglis6,iv:9ClgM9uGeyOccbqhiSvBVAjMhiIGnLowmNhqGcatK2k=,tag:81kQUPlT1NPMKfl1RGILpw==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:TKKgQVTN,iv:IbDO64SkBJXfje8KPIbaPt1k73xhRnei1sNlCP0qkRo=,tag:mUToCZcF6CppT4tx71SLlw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:JFudnQT46e9BGSuKlpXKSTP3rs8188uF,iv:YJsqpOLil8pgTos7dlHWyXMJP1XVbY/QnVQ1H/1aiv4=,tag:IhrJCB2okU/2cVDdHezqjA==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:aJet/hpeYTKQ2KrbBx2CZf8M8oJ02cqXxVP4Ydg99NRc+NlqoLCzeg==,iv:aece52YQJU/kvMd5u04MvY5MGHGlCiB1ZR1m5tqBhn0=,tag:A+B4dL9ICTHR4VG0rsVY5g==,type:str]
  DB_PORT: ENC[AES256_GCM,data:efilag==,iv:E4yAaOLpcd7e/A6uPzUm/lV/BqArynW176herN/xM54=,tag:awVVyCd4cNwk8MVx7VQ9DQ==,type:str]
  REDIS_HOSTNAME: ENC[AES256_GCM,data:rjYUL0emQgEAHmfUv28Ijg5O4vqczzEaC2Dku7jh5nM0PH0Z,iv:a3xw3SqFOqmCu4BlSR/RYqo3KNjA4YOT8s/FVywxtXE=,tag:NTBcAYAInqU4NCebDBND2w==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NC8yY28zUzk0TTB4SXVM
        ekNkbHZoNk83c3RSNUZOald5L0c0eUYvMWtRCkxIT05zdmdTZ21rSXdySWc0SElt
        dU95V1JlMVlTcG5PNUVCMVdRb3hzV3MKLS0tIFNvLytDNGhqaStaMGN6bVRCWDZr
        MnRueUFGTDBmMmRCRCs1aVl3bEs0ejgKX3eEmx4Px3bDlW9v1bhk/VGRZl1N4FT/
        obpp6wYSkXJ6WTyHwMo/9bYBLo/+7d8BQLOIPEWYWuUG/gHNVhJIwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T17:50:50Z"
  mac: ENC[AES256_GCM,data:SUY/rwrDLgJoIxqhbz+F8MrFr4ZzrV1hyDty/yiwSYymhQht3kJxKIwz6mSTqguKDHqwSz3NaTx/5l5cgkspEHR+SNAPmRwuZ+N2yGbLzb6ymfmcWPObxT8KjlhA5wHZMaAYea1WRc2mbKQsTYcA16QbQqM+zQ9pDbNQ9iVygYk=,iv:NhlsMqosp0bn93OTkzt5SfGGXVsFToJuCTnZTlOTbhk=,tag:842G42kr+D8oQ4s89vxeiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
