apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin
  namespace: influxdb
data:
  admin_username: ENC[AES256_GCM,data:C+sMVnETWVw=,iv:gj37trXH6IGIBrCqINmq0S331V0eQGRociWqdqn6KnM=,tag:yPu46HCYnugaQ699RqSnbQ==,type:str]
  admin_password: ENC[AES256_GCM,data:EJcL57CMv7y152+ohng78g==,iv:/dneck6wgW8FYKt2e5owRRM8ndPv/prJZecEmf0EH38=,tag:m+i2o3W4F9TFaIHwUZ8IzA==,type:str]
  operator_token: ENC[AES256_GCM,data:pIS3gEmT8gk=,iv:l3AUB4Gzmh8GiCtV/V3wMzcg1YpeVERZ+XnUmnQEH0w=,tag:8dm+dRI/QgWBZIRGTQLm7A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d3F4ekdrR1R6Q1h1OWhE
        RXJieG9VNHBmeEVESWFueG9FMDFMa0E5akY0Cmx5VHRqWlBUZk92WXFiZ1VXSkU4
        bU5MbjZKM1loVVFQOWNVeCtXeU1XZ3MKLS0tIGk4RzJlSmdnZjVnTDNZQXJvRWpl
        djAvMk5UUWZsYzVNREV4ZmF4Q052UUUKnjNxf04FZW504gT8/ORgdehgYzO4DVZA
        CiImp7PH/OOksLmd1sZd+a6aDAkDkqlnGaOy5A3TMxgaQPGJHSIdEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-12T13:45:14Z"
  mac: ENC[AES256_GCM,data:CPt4cD3CawvjX+YoUNdIOQcU6X/3Plcyhgziv++YheIBQm8I9Fl10JXYK9TYxw71fu0t1BuOYkHdCgGFQRliT+mwTb04e0nInagGYTNjan9xp1S0xPYe4kzhF078FvC9LX8mEJoIr4Z/YKP+Nt0IJGBWcnEysuDkatrE+EgIaKs=,iv:6cBopOsrKsZgDmnUOS7mZVP6/RpiSHkL3P6jMeTUTbY=,tag:QAgkLK+jwmoMnoy9HuPO0A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
