apiVersion: v1
kind: Secret
metadata:
  name: multiscrobbler-secrets
  namespace: multiscrobbler
stringData:
  SUBSONIC_USER: ENC[AES256_GCM,data:tJrZiUfSIIQ=,iv:ad3bO6XJ3E/3aRdydz+BMPkCdmz6GDcxg1OXlJ5jqAo=,tag:3zGo+8tX3QlM3G5WkmIAog==,type:str]
  SUBSONIC_PASSWORD: ENC[AES256_GCM,data:QFeH/Jl73oK5DE9DkLDAC57wmg==,iv:YaaBIlua8kSeTMi5YTFuf+Xy6ij5M6dh+o/2+Su5Zwo=,tag:MhwJVdiLUvYbpJdqUuQqVQ==,type:str]
  SUBSONIC_URL: ENC[AES256_GCM,data:+d8pPDkUpKAOdwH+OeDG4JuKoMsfZhxCBHT8f7U=,iv:u1noHViJ/Xhg8BbGT0F4O32HcMo/0m3EHtqTTf4P/so=,tag:lI/6tsbPl7INQKBXmQQGQA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S09JazRtdVRXMWJwLzR1
        dEc0MHFJM3lIRkwzV1daWnc2NmE3UmtpaWxBCjZFZm9HMXlHVElmYXord2NMYzho
        UWF5ZnQxQzFTSGV6RGtYSEpsVXFRVEEKLS0tIEVJTkYyOGNyTC9oU0pzTzh0alhK
        d3d1N2hKQWprQW1Xdmc2NHRneE9RRVUKm5EEne27w1DoKyLWl/1ab81G5hAwIyer
        Ows+itRE41gAjZqg8qfV6JPTISECkfLQUSRu3a2EC/gUcRe/TfkdlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T02:42:28Z"
  mac: ENC[AES256_GCM,data:UeqmPJUeYu8sGOlw4Hod6SDiZKndfIaKQbMbSC4rODCDB7FSq8Hnm9lINfIyoJjGXyUcuNVLj7pap9h5Ug75FgJfROeCWOgJLPYb5pUqHltrU8blp5N8iuoSiNSo59n088SnFLJPjO/UfL1xsfX484V1EfhWd5tGsQwvbzorluo=,iv:x5thGCZpHR3Bqzlr7Wjz9/lll9PofvnhsL7P0FvoJ9U=,tag:UA2lVLR1c7mV4ELnuxLcIA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
