apiVersion: v1
kind: Secret
metadata:
    name: multiscrobbler-secrets
    namespace: multiscrobbler
stringData:
    SUBSONIC_USER: ENC[AES256_GCM,data:SN5/KXePwUM=,iv:lgXXYn6ULAaruDfeuOX/ozsaGVmDZs/16wd3sMWf6j8=,tag:IWFzZAq3vl95vIvM7+l4kQ==,type:str]
    SUBSONIC_PASSWORD: ENC[AES256_GCM,data:/Z+nsi8qEKsOYxKhBpDf/gQ8pw==,iv:pYR81/0hD4T+N2cQ08fpnGWhPVumomi/TDNU2QLJiZU=,tag:reHZhpvKVCLIHMNX5xzBpQ==,type:str]
    SUBSONIC_URL: ENC[AES256_GCM,data:EyEQPSrskghYBUf4avidc1ShMReAkWkz4KyuFMI=,iv:aoLDM9i2cfDqM/yxbzKMA1xaZAU1/FiCCzcZgINzuVc=,tag:uRnb7Nn7DhD2lXUdUIZURg==,type:str]
    TEALFM_IDENTIFIER: ENC[AES256_GCM,data:auLBSt+OWDK8v88MvNGNxA==,iv:GNLbzxki6pS2cuZaxyeNIDGv8q5KnrZBuVcA5RHJKKo=,tag:nlCDZnsIzJqm0sANo39urw==,type:str]
    TEALFM_APP_PW: ENC[AES256_GCM,data:C/VaRbgD40Dmfxc1g8rAlWB09w==,iv:yMHD4ozfjqfnEa54LUllm0RJ04iuRo4NUziA8GtP8lM=,tag:j2kEsPBPNxsekAktTYutAQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUmJlK1hLTk05RVdJSUpa
            cEdJenU3cDZSeXFVYTRwSHNLbDBLcitneUdzClplODVvQ1NLYkU2ZWNjUWV0UFQ3
            NWFHYVhhSnBlL3Bwc1Bmb2tMSnpsSEkKLS0tIC9IQ0lzdWZ3QWNBSC8wT3lkbXV3
            YVRVSnlCVE1DYjR5VlQrWHM2T1hZbTQK2pY57S9Gv7cHSisZMkJVdCf6Ty5akUNL
            lFUc5hvFG2EWY0kE/oJ/1Hb4YSVfw3SYjmvy8alYZ72JYnKxKwNBhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T20:49:44Z"
    mac: ENC[AES256_GCM,data:6GfYl0oiU9lIXxkxAheQB1TzjDMaMyrvP6Yq/+Zo6VFU2nsEUTBTASCiD+XUtqZKqaj13NBRp/8eu/e/9OX0y9YVRjjaIXRyVx140RippVn6j5SWy7mPf3df6469C7mRipAXOlrXQ0CMG280XJt9QyONGGwFCjZmpjt0oN6JMEA=,iv:FuTCTKOK8BJHrkd97Ku3fUQcsMlvGC4027jv7Xby40M=,tag:ZN/NMCGflmaTMe0ooWRnXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
