apiVersion: v1
kind: Secret
metadata:
  name: multiscrobbler-secrets
  namespace: multiscrobbler
stringData:
  SUBSONIC_USER: ENC[AES256_GCM,data:7DXkchFACLs=,iv:8D5exgtS7eBPZOXjOzBnCCJ1oAqeSUQzoG/pbmjIY1Q=,tag:aD9FN66M/TidUPO8AUfZew==,type:str]
  SUBSONIC_PASSWORD: ENC[AES256_GCM,data:t6b2PFvISNM0+oPzsDR5r7zYbA==,iv:2yluVj9oVZBZ9JI76ZrjB44GxK31UWccuSELrAFLtbA=,tag:GXVFZALlnsb4xXR2uFTVNA==,type:str]
  SUBSONIC_URL: ENC[AES256_GCM,data:IOusK3yJkLXSaeKjMcsBq69jTt68e4MpQIcyhaA=,iv:SLwdcmRt7ZEWNkiiE/Wpx4+s3/c+nF7qX3z4mlTzvqU=,tag:l4N2G+qizdUgEXlIihea3A==,type:str]
  TEALFM_IDENTIFIER: ENC[AES256_GCM,data:tqLRoO7vSGgTyfL1q1AFhA==,iv:W5THkXHwbe6UztmAxmz+IUZ8YfKeATgKdmUvpNs+Bdo=,tag:Iy2SUrAs0l/HKd8Oc05LGw==,type:str]
  TEALFM_APP_PW: ENC[AES256_GCM,data:bqmh3T6WikRBfqO8sncXoH45IA==,iv:+3QUy+57veNOmdhm+qMScJkCxK2Ev+JVY1YYq45iEMY=,tag:PigMrJWcsWVU7Lssg5rdkA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlamQvd09MOUZDdy81dWg3
        TnhQcFFsOWJqTWZJM2RFU0kwb3puNEowVkdvClZUelpraWppdmtCYjR2VkhrdkFW
        OGR0NVVjUWk4SDZSbGxzZ3hMV25qUEUKLS0tIGZSamdIbzQwWkRuR012SzVhMHdS
        NEdhMGtlL1BwVjIyelBOL3JnbmlsSnMKNa+yythMqiwJK9NkXrfl0RjJrhZPx//q
        AoGdy4dRrD/X7dOnc4A2rD2dElAJ6Zf0u4EKv/u+Up/11s8KLh1mFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T02:51:19Z"
  mac: ENC[AES256_GCM,data:SXyjyJ0ARpkOxubRVYTg3bNrbrXdnmIfDnuA/gTxaD0q7NrDmstwwj+wJhgsUu0LnNbsf6BS7hGZapRPvAfxzl19lK2RdhOjL5311WFAe545l+btDIE3/bj3EOYy2be4Vi7sUpmi7NaGy76u1XG8/SCw4nBOw2zzcvVfvfj0rMM=,iv:r/QTYjwtdRFMfr8pz7asxRmkSOTGOz7VYgOOzMhdJIs=,tag:PyfwZ7Vl4AE8VZAXxZY/Ow==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
