apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: ntfy
stringData:
  NTFY_DATABASE_URL: ENC[AES256_GCM,data:QCmNqPVrIPnFU1sFJI5iGuevAe9xO61vsIiYDqxqYRd64viGdpQ9pZtKAqS5srCjqCw+MoHqMSnEuEMw4onD7AOkXO7b/jc6pioGmM6IjzoB0M7/DgboDiAUIpfpYELg0qpQ,iv:BrQhhrc1+IMhHHuMV/fN66Fz3Z/HkmHzplNSdU9hIyE=,tag:ZsmJTIPBjmdjhx4AA/pgbg==,type:str]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:yDUs24WWctC8YYXdVf3HX8364irAPiHhBRXeuGat09+oQTbefgokOYW2za/vG3tgcH6dfeLkm3XkYkwgacFiZlGYZyeMN551ZGNt2vKdtHd1jiLrlasI/NwhF5tzgbw+FtBK1o6O8XFDZhQ9U6wYiCalSOxRv18f/N2rcLTMzFh9Zw8A7180u4QMoF4buD/otIwA4bvtW0JCti6DUuZ+ZQtwcZ7PCgFWl9inqF11lCFvOl6iky7sruEyvoctJsxjQQHGzcaaiLeiiPlO+cuFLWaIYkQb4K5mdBkIpFQ6dkUUHSnWx0MVzl68War/SVeLRcO61UgY9SPt7zaenKRKZ3WQNRux0DwMYz+uO3Y8r6rMBsiw5e2oNVPANrI23QcVIuPd5rkButVM9NpT,iv:XOkHFizSqgN87xc09GV8noqLVXgmHfLM/4R++T1qms0=,tag:fsFDaPOkPRNEM+aD8Sv1dg==,type:str]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:xAxrqteKwkmx6P+2OqCga5MBeH44cMv2ujXrJzP0Br6vD8pwBAw85WbGQ80y9hjWybcrY8lf1GqQkpAVGKUm/ordq4Jvx69yeD3UsV62iX9sSXrMyNqzRLdhprI4QcKrRe8DHGW5WwPzbZWyac4JCzpYaEqlSIYIP2DSG/q2LizGdpLAmML1f0say9wrIZ8hReLfS2cR8c30gA==,iv:OY+0LFvzjABNZGNMRd046zOVArhA0+BmFexNxFroIPg=,tag:5aOq0g1WPu0glFXyBYt8Zw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMzFIV29uK2hQTmVydGdY
        ZWsyUmZxb2ZNcFpRRlZGY3RrOS9hTkNOOTNrClNRNCsyVi8ycjlQRjhuM1V3WEZR
        Zi90dmJuMmc2OUlvaGsvQkp0YjdyUjgKLS0tIGJZWXdqbmVRb2J1Nnk1M0dNWkg0
        QnhvVmd3eEVYZFlOVDB6SVZVU1l0eEUKTHqOpoDzdbFOpxX8T3e9G/w4SxRGWqC8
        dfftv7AbWAHBYtdtzvgbkzunFhMVSI9Ob8Y7uV5WYOICbHClWTtjtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T02:48:07Z"
  mac: ENC[AES256_GCM,data:h9hqK7eoz2TY6zIMl0f5Isl/Pz6pnSiJJfdzlgCSUZB5EdoJIbjhaC6u/scw7Yf3s8CaO6N7i+7e0+F+Sqei+P9zVIko4yickUAF5lPak9baEO/1FQ3NxzLHA8YFWTk0XYkHSwOFk0Afu2nT7Ev0HqDanzMr9NbLyY7itZCpNq0=,iv:7g2klraGCTuGaiF9xHjRSP7hnBVotBRtfGUOSnfMAMk=,tag:mLRBYnKJq1qHubqbg5iowQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
