apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: ntfy
stringData:
  NTFY_DATABASE_URL: ENC[AES256_GCM,data:24ZjA9bjXDish6vLZrF+ES8mdlGS1dUKqKaJ7gtEI2XMXhLwZo317GhsXBSU2RplRyQrCWrqZ2OecIGDTIsx5v0tj59Ep36AfuPSMLDL9u6m4abKlA2YX1TwM/iAs1ugA55C,iv:KX3rZCAe23fDNEmD+Zi21h6lMH38da+paEHQvBV8EAw=,tag:Q8pGaR5dhECun8apz+qKTA==,type:str]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:hoptaChgUixRr2jw3A4bggW2IkobqMmc8d+C59KPyrkYMdH1ziLlGpfPBqscDCZcdnLQivR99zppIfW/iXgcfi9kBZOTfhLodKWBypMq+d4kdlTeFv2/zbiT2V28kc6+Iezttg1V1WrBfZCATx3WmUs9zNBouQeBYxUNXdUgAPshK0Uor5meyV5C6lh9GrNIfj1owwVAKzp1e5EcQo/zGStbUeSVgVlTf/wjxwfY8OldguzlAACZoP2gvbay1EFClDUuTMfT5Uh14M/qj3sp8vvJfM2ixA1hRMUKuQG+eNs2mqlvzC179I5cMWz1llTCMdGhvY357AFC9b/S4ma8LFAtNYCPVXHosvWtXddssnjjp6Fqrwnt5ziRjBh/IQAXtybCYyNdEhkNcDEUwQ==,iv:RkLunjhzATbWoyNLXPrfyxZ4dczNfQzDz5RwXX9Z2t8=,tag:e7rfxCm64SzUU1thxCDUQg==,type:str]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:PJKdsIBok7yDz6rFUcs6SJi+mGsbwWEz9dhG6TvRNocfpT+4c5rtST745KiP9AY/VYyHjCJR8o6z7IweDlDwc360ee1vTcdx09bMDFDj+KElDn6zm192KjRsHwYxDXrbkHfVH7KbrMtbNXPgOzrsjm3Drt1tBEeIPdg9dAH+WNe37qsBY/Ac+PRL6NDbxApZzZBnmnW3X0HgAg==,iv:u1UPlo90Wo6uEn7bpSwA4OyGCi5W5U8U4KYfd884pPg=,tag:rvgDEV6aBr9e7NSs7jFhgQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ME1HNUFmNFZVNFRTYzlt
        a1FqMjB1ZSs4dUhtVG5YbnVnS0Urcnc1b1ZRCkxQM0lESDF2SjZwa2RiK05uOVFR
        QloralRuOHRkVm1ZaXlNZ2ZLZkUxQjgKLS0tIFFncndrbHhqeTZHR1U4QXVaaWIr
        OEY2RDg0bXFsZ0FDRlYwT3hITTlMTTgKw57DARkRjLa1ayMabeygD6VCO1H1lGQP
        6SyrYg0mrArXHpVyCDjamlIfZrkL0GfnbB5tPSMACytN2JTK3H6zqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T02:50:14Z"
  mac: ENC[AES256_GCM,data:/DVEfHpfrhyBwsrK3V2YD6vvJ1DA2cu561AMtIRnyqzmQw7R6qIZu+3BH54MVl1rkhkp5MQfSNCZIBk/Xlcd/eIjF4XdkFM9yHoDFAuEb6bwDuIAFul6NiTx3JEUwSim3cWaH/o1Dm5+AcGiQNXiY5rTRGWDvKU/g13ICB3JeGA=,iv:115wi2EP45+KA2rCg4/8MeiXIj87D1JPbQIOgTS5t7U=,tag:+GB09KjI/jomWfa+WvxbFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
