apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: ntfy
stringData:
  NTFY_DATABASE_URL: ENC[AES256_GCM,data:gm8pigvvE53EQUenLnRuxSjlraES2F6CXHXsk3VwzQNKaBIdclhUkBPg4r4XM/JIKHBio+fTLCXKWBSiGSojnHg1QP9kPFvK8bNnu2cnajA135dBboEHhVqcqMns2ry0hhTX,iv:eprSzujlP+W92+vbA9qDPEU42xvRfb86SOfJp7ITetk=,tag:l+IpNK2ca4LkkxXC9ATjjA==,type:str]
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:hSSo0tQIsIANBg4OMhHQK6veiK3Arj+BqlZbOGfo3OQoKEuMQov5xUOKQW7oToLLyy/fRXe6mTo2I42Kl3jQfm5B/Ao7A5DluCdhhYeJkwP9GoHfRu7P1hEig0O40Df8Z6AiRa3btGMPEKiJd6oMDnuDolQd1lZXNNbidBFoKPonQYsIUWqvirTA00Y1BWsPkQ9f3t5+Ugiz4pRRFG+DLS0qticL62PuQ1+j+KfUcYDk82TpoJ7kQxCPr/QVGli06dJXC1nJlLWgrZJ9ZrO0NiSPnW6OpNZj6hjrJzsmYK7kAF/Cgm9gmkEktMzYdtlIgHQeJ5u6VJRRM5yAGsm1fYNlbnfvSD7EEr0KYOW/22Ngu7SLbRyuRgcvgcIfbCXoXrxduIwh0ELGISmqJA==,iv:c+yYxSqNwmhWYfK+Nups/HmXVPSEsjvQNxEpVN1HYkI=,tag:dwmsGiN+Gh5P7X07WOKOPA==,type:str]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:j5FbGobEL5t17fOYCGOI5XV7d3uDZQP2S69ajlzB2SyQcd/y1jwm8xAvUvryI8chh3gJxqnbP/KP0lgFjjxNO2VytXTxp+nAkRNl7XbaxHp9eqEdJL5x65ugKog3AbKx9t+ejccy+8DSH/l1m5j26efZ6Yf0Kg/bFtRJ8VQ9WrsyFqL6rCtcwvCFZ78vn5MMUbnaIsNSWlLw3g==,iv:IJs9+qlJBipw9DRGSS7H/FZ0A9wsqSD1nDY2BdULW9Q=,tag:r1iRWLTgUeDQ5QBHT5vsrg==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTVNLNnIyOEIxUVhnbVVl
        d0pMelRjS3ZZc3FaSWJ4WHdzWExYaFQyVXc4CkpnV1NQVXZEdlRxRExEcXRzN1NS
        Rm04S3plWDhaNFF4TW0wMFlWMk1sek0KLS0tIHVEQlFDcjRNRlIwQlVWUEVEbFBZ
        VHBWYkNIRWhiZW1SbEFvakdLbTh0dUkKrZyKeVdeXQ6peG92i7zMYeM1TP3YWqtO
        j3wg6wSzS4er4vHZWRlao7PH2q/+NvM7Cz75hbSWrQMGer8DZWYzRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T02:55:13Z"
  mac: ENC[AES256_GCM,data:Deobu+78qU97o9Zw1gSOM1/k3TrglMpSubLHWvpsUrYwPa+Kjse04Cv70Mx3uy+plHkO57wzN/YCZUQHDiATD4OgD7wEjNeyPVFanD1Zy7FXOUbFe8+AeVbMFVeVlwF0GXjl25tl4WMGi83s4irlklOrF3zyF6o8GsigcvGanC8=,iv:sme+GcO3re+gU89YiWuLrKANprGlHCM9Ntxh3ApDbdA=,tag:xuHDKAbrOS6PvPBHWhCcng==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
