apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-dot-gw-token
  namespace: openclaw-agent-dot
stringData:
  token: ENC[AES256_GCM,data:PwY9fsdD0Qs4WTQQFKFin4kuiOMgf5jb0RS9zQQLzFXYHjasvr5h4hMwAcdIT1G8PxC9qYgvy7C6bycTklnZEg==,iv:HsvgzGIeGRex5W+AcU994BY8BBQFdKZoX2/c7kAwAzg=,tag:i7yz93BZUtD4EfGKR5LzVA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeHlNN05vczB5K2IzME5k
        SUZUNWovbzROSk9IVy84WVJJWHRRV0NxMWpnCnI4K1ZIK2VaeGVEQ0VuYlZwTHNO
        R1lhZjVTRm5wS25scTV3MDZPR2FiQnMKLS0tIFNSS3h3N3FOZlMvb0xLc2VKZjRa
        YXVuRFlyNml6ZTNpdjBpZURpNTUwc0kKiU+duxULfPM9DzeLUCEmYnr/qHDkax5Q
        i6vqUffZ3PynmvS1gxinUYzc4ro2w7rZ+O9p609eiIiayxxrwc7P0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T20:01:06Z"
  mac: ENC[AES256_GCM,data:H3wg/0DHElSyVAh3CIrQbYci7QsSVamjdYtLmdgmlggDKsM6lG9OUC/gCuq7KSqL1C32jQXRBVAzDMCy4s+orX4K++QZpiGd4UGW9RvLsU+Im1webgyZsbHvVdFnHOKe4d6LLRjGbxByfF7fhoiI756EyDITH8Y5tYVTj+90wLk=,iv:I2kL31ew4kwLFWDBkPTb+Gwl2v++wVQY01PylUWjWvc=,tag:FOxPkVdGnz8h3i5Y8HJzyA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
