apiVersion: v1
kind: Secret
metadata:
  name: openclaw-api-keys
  namespace: openclaw-operator
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:NOhhLyl2JUH/EuUDb8EeNDKyI8wl8pJ494JTZooiMKJNzrJIYsCFq+XS41e86gY66KLGP8s07DeeRI0l627d3sGkxK3pnAoHNg==,iv:xHSbUxQn7mGkP2BTlp+slvMUSgPIXWqtd+3wb3AmALA=,tag:+Nk5oFzwBcglU9V1XKy/Uw==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:ZLMh88ycA/TsQ38dgTwtHfeCXLYcSu4GXVCmimZ6pmE=,iv:lW+sJcyaaUP7F3kbUSIaj5iDk3j/DZsyiPWvyBCdVwA=,tag:p3t9ItO1qfJXmILeMZUTBA==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:ufIjM28mf6mj24vn+czB8ImKQTuWdOktvdUi3YRlDNB+U4Oab/Oo3Q==,iv:wE9X91fJUR2pR605yHnzCvRSIOqF+YNIxhmdQ9142mw=,tag:Z2vOU8ppQI45jM0FHCa1gQ==,type:str]
  AGENTMAIL_API_KEY: ENC[AES256_GCM,data:sfEpybhb7blhbnZ1ey/1MCfLM8lFRdqgRlLBZwVDJOr7vpFE1luQz4ceoWhgV2R5cMXngpi11mT++s9nalydR2sDDMhJizewf5s=,iv:0tphQ87sUziVFFKRLx63UwyLpIxVW15a1SytqpaqYxI=,tag:g2kRt34fbVGHZxEJlSf9jQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeVlnRTZMVktpZktWYmJy
        bElCWStVM3NqWEFCSXk3UFBZeFFrY2VNT1Y0CnZPY01jMkwzNE80blBCV2E4MFFN
        aDN1SzArc1dQYU0wQ2lXa09TQXJGcGcKLS0tIDJ6UFZjRFZoVXByZXRCazZPcjJj
        RVFYWVJrV0k3SVhWbjR6bkdEUXVCNDgKkEi4hzrsq9TVxiBY3QDZmQIDMIqizDds
        hDBc/ov9UgFw4LhvJSV9S1aIsQBVxT4dIIsOQ2w+NXPcavnGfRPmrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T02:55:24Z"
  mac: ENC[AES256_GCM,data:mZ7ADWK+LEBY8TGrkgVPYwq4yBg/EztfWWaA5mUnLM3wXoAD3aWKbbyFrlhX8HIH6CrURAKjM5hvNIZo8Zel2yMxsZWYe5o0xKOC+1QfqCNM6cEzBmGm7EOZRvMCX1zm4/dHYe++Ex8l5q+z4Lqcubu//muOJxjkCuEhTiHvPbY=,iv:tTWUfA6HgfvsTA1KRCHs3ly9LkjiV+BXvbX0YlBn2ww=,tag:nGI6bq+4PTHSKquEwxs0Qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
