apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-secret-files
  namespace: openclaw-operator
stringData:
  client.yml: ENC[AES256_GCM,data:B4wOgRhTs1pG3K/uaJsjTr7Rk7XAVgPSNMvF+yl+lX9es197TLRIbriXkamLDC2IJ5fGQzUc7C5cmpCBdZpo9DIzJVz5lBBkbwuo1XUicRxQ+gemQJH01w==,iv:AznQzmk5az3/UBovy3Aml2T7GZNvYCaVosSV/QDIxsM=,tag:0JdD3TvSDJSymzyMZb9ljw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNGtSZXFXOERscmFSZlVv
        TkJLWXoxdlRsWGdIblVnRWM5K054c0NGREZzCmh3YXpxOWd3TUlIMnNGTFlRakIy
        VkFDQU53SG1ZcE9DM0ZWbkRPeDFiRUEKLS0tIDN0LytMNlRpNTBRL3VVbHBkWTRr
        eHBYdXFLSEVsa2ZjaHFjVTN2cFlpQTgKu+NQNaRUkjbrnvCK0CaCITO5cHjd7KjK
        lxM8vX+0NCnc3SUaMOGmJeIw3C50zPHH9UsDcIyM+hkeTenZ/iIvFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T04:09:02Z"
  mac: ENC[AES256_GCM,data:/aoBOembb+RTfxfdkQJhX3V/81cvgCEIwhQhKmL1PoKkxFm8NQEIpcTgw2Ix3z+ULLxeobH509eZN1C9Z7Zfvav+K9qfv2JeDqRcgqUOS8dDbcE+NQqAKbxyuYVhlzKAA2Yq1FMzGHQuOdkxM9lJQijv1v9Wha3G+GheX9MyhJo=,iv:jFrhH5R1H4rjtydmkbmGdJ5eAx7ieiSh4ZYR/gdRaAk=,tag:R/joSrNj1R2hM0BL8AsaUw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
