apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-dot-keys
  namespace: openclaw-agent-dot
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:KhTRy4Xc9gg/tanXpF0SVNNYysRN7yATHOQdw80kB16JTSd3DOknkibe8GRaDoNP2rqRXYKhu0wFX88QWk3dFUVMxHemULKbHg==,iv:JCjxTScrFZ3ZHx3fEPUuBFBj+sBRHqa4Zfud5UYHaY4=,tag:zLLcrM3m5MYYYINSn7T0Fg==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:vS36pDSFJAG9fhAbhp2+okbQ2k5DAngimgoGumci4Qo=,iv:YzbyUpHjxHAd18kCnUw4XEnQIagf3OyqN44pLWCmBDI=,tag:jrKXWmKz4OezJPmk5oF/Rw==,type:str]
  BRAVE_API_TOKEN: ENC[AES256_GCM,data:EvTDbW6FXn6VYufuEt7lz0cIR4Y7wgY4C9vywUEkzQ==,iv:Cofamw8SaYAQTl0mAk2L4fc2ADq8kqfP+Zh0mYblkAg=,tag:NYlfHJ/Fq/PqBo+eResneQ==,type:str]
  GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:8oZzssKdetgVEuCIrg==,iv:QpZPwfdjtCv1x3G2R5ZTRXLH/jlDwZlegWn5IBUXsMQ=,tag:5BHax/kn/WN6CgKRv50uhw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd1dlVkxkNUZEaFdQTnR5
        dXFIQkN3bjJjVlZpR09ZRlR6d0MyTkorcHlVCkszSGVqcDZUVi9GS0JPZ0RjOU02
        Ujc4RVduZitOa3pwWFFucGtMNEU0VmcKLS0tIHlsbEw0SU5lNU1ZbkpTaXlGb1Yy
        V1l2VDRtT0RzVVA4MUZCeHUwaTdCZ3MKuJY9XIV5GXn51WXXkuOKcCvNoC9nalNY
        C0slUaBB25GIVojdkCUOuS4adQEc+zTyGgSq86rCaPXuuxnlJmUvlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T23:15:57Z"
  mac: ENC[AES256_GCM,data:hqtIgQG0Iv+GsSAG+EhycQsGNyn2HhJMH0vtxGgb31pZieoxGMg63mCwydo+P4NVU/zbZsPL7Deajhip13RGQu4dYhTPXWVww240E1rfUKxH1wVB8iu1UfpmHrn6cVZcH3GD0jDlcemsaBW6Emzvrun6cTgDbF3etGcaVnZ5B+w=,iv:KFSljM4kgbBpRgoY4gynb1dLvYokUN3OL2ri1HTegLw=,tag:hj60UUmkLuk7NlUH/xesww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
