apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-dot-secret-files
  namespace: openclaw-agent-dot
stringData:
  client.yml: ENC[AES256_GCM,data:huYpYQzpgWhtZfEtCWFIWeMpAp7ON79wEZO+1yUw+XG3aJBiUnotWUp59+RTqgonVdRlMSVr0FS3o8ROcOzstajTssu0B50AmjpVb8DvCZs8zs/LImV1gA==,iv:FUNvvBZ+g6ZSSxFIH6hAjjvcBqK3LO0dIHvnhQXSEOA=,tag:2Y+Xhx1w3ZDzIgB3XOAfeg==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMjZGYnlJYlJTL0FHaEpC
        eXkySzBPK2krQWxIUktudm9VeldVa01PVFZVCmRhR0wyREo4QmNOR2RBYko5OUQv
        V3dJS01QQW5oUmpvZkl1UnkzSVdQdmcKLS0tIEYrUUF3Z2VSMUREMU4zcnJzd0ZW
        WFFuMHhTZTZweDl2eEVoM1hwNGduaDgK83WiHL1b1dOjGAszg01EMwbv6LYLTgMH
        5fUlxBHw9SmiUiKy+Ow9e3y6cZXYUFMiYGQs4rOfQ/+n3TzEux9uaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T18:17:26Z"
  mac: ENC[AES256_GCM,data:NpVECVE6zC98usPS3eNVuirIKRUivFoVixI5EMm4Ug2AFbmhSpsLi49y7gr52Qz+jRSlKM10VszlkddWMpuUquoW1iiFg18iPYQSDj95abLHvZEA3RP83WNWWzRESTiyTSZYMu4449Vbxh1NavoqE7QvFYjQz5jp2iahu2UMyiw=,iv:N7ZF/urf/VRDcFFktDLkiMmWf+Qlk8wP6j4++pYFG8w=,tag:Q+uemMmpZlXBI4B2EzP7aQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
