apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-claw-keys
  namespace: openclaw-operator
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:HkE9rHbt1Nqc4kXQs35ITHfAKRP2L5gGtJaIKK+ykUsF2iI461KXYTMMXzRik1pylxN8hnyqmaShP0LX8JHVmGHRxzhFDnbxMw==,iv:XaVh/N+4cci9HxtZq4HI45y1afDku1ehj5wiFUBcGuY=,tag:4Y31V1UpI7inlrNHvRypew==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:DS6zcwROTOSJaz5rVLEf00ijKnr2tsM+49rbK2dpoKw=,iv:nXNKr0ceuwP0dKlG1rt9iAQJZeWJPV5bRTJLgP8o8mk=,tag:YecmJxmeLod5tQbUXrYyIQ==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:qkYGsdJ5oMfx857vXU2ElUwgQcgr/0tt37HrHsERC2qaOLXj62fSQw==,iv:eeWH7Tn8e+mGQCG9jgVP2BsPxEmsFx7c104/4mMKFQg=,tag:g2yeWSFJ+84xR0FFxBhL0Q==,type:str]
  AGENTMAIL_API_KEY: ENC[AES256_GCM,data:Uk+tWnRn/n/LB4zgxjsbf8JDz6cFyqHpTc9Q3//yN2eHhmjxtySEY4aVoKwYF/ExITDeP+XwYkNQas8nxCRQA8CzbRPq/09R33w=,iv:3SzHK0EnYhV4B72Zd+ftJtkhvIA2sjVshI+OqU7P+Kk=,tag:yvBJh9xB2Mv2nB7rkR5liA==,type:str]
  BRAVE_API_TOKEN: ENC[AES256_GCM,data:iTAhtK7jZk2UXhu6W006E8WjISnZZNrY7FZ8CVDudw==,iv:GfF6wP2/nUdRkGNRNktMDfgi3nAw78rGZ7jr3xJHW1I=,tag:6ufre20LGopnxb2KPAn6aQ==,type:str]
  GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:5cL5BBPOpXXitABfEg==,iv:T04sqsluXFkK6PdkRs4EnV6FM7V3s+WSrSiy+dxGXpA=,tag:ZEE8uv4oFxR9SVP5gZmwOg==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSWZoZHNiVEJBV3pVSGhS
        VmtLMUhBNGtyL240WnhqQ3RYYmw2b1djWlJNCmdCYUdFUzl0cWFoc0g4ZzZESEha
        NldNK1lLS1JmUUdZYzlraHlRcGNXTVkKLS0tIHBlMG5xZnZuYTVlOU94dll6TTJk
        eHRGVy9lV2tPYzR1WUFNbGNUbVl5Nm8KuoYLkfGxyNptzq7bRzued47M8OBsKnn/
        aZUcqN1OyDNvJgDT9i+GZ5VkXwcMWZzCdDWyQ3HkOr146coRgN7ujQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T01:05:23Z"
  mac: ENC[AES256_GCM,data:fJg/716BIv5pGj4srfD1VM8v2r0xb8oq8B6AnISzt3IpaAKyxenEOULNup7RP15eVBpOzF1FPVUmYCmnksEKA2CjTq/RP8zgwIIpXopLD8WNeTpSwwndXaCSMeFQYp4jN2BPFSoM1nnxDN95+XgAc4jKCU20HjkPT6NBtQ2bDis=,iv:MF9I/EN+B+cHQNCskKFZTT6guMt/jH+WekrMaxiUxas=,tag:NaLLyGslXH6zKf8pLUshzQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
