apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-dot-keys
  namespace: openclaw-agent-dot
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:QkE2OmDaQqvH3luEreAAX8PJn0DOdDwWA2gaoKQ+Ft52AnDNo+c+vGzIdZ4wBu57e3Y4b+ZMlMuTqF+JSrzRFJrk8IwJY1We0A==,iv:jF+DdXbtq74sPS2lOAuddNEJQcHYGLZjmyrV+buxc9g=,tag:eR+oAyjPB/uI/qdQZ4/FtA==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:6ETtJooYXyvYTNcL1xK4ztDA/FXEB6JHIfHfAP2knqI=,iv:ZcIapj3rTZleVplGVz7dXhYkv76SXxucr0E0LFo7/TQ=,tag:Bou9DnJSQ397qA/mHwBW1w==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMVBHeUZ6eDdCY1V6MkVJ
        ZmlpWGlORDNOcE1mRnNSZlRnN2d2WmowekVNCnlkQkxCbkxLYWhvUkVoQU9jUmRQ
        MFlqc1pNNkQvaFpDd0J6N0JBWkJLOGsKLS0tIG9WSU91aEFSSU90TmNlaWNWTk5t
        ZkFUaUVPYTQyY2ZqbkIxbThWNjhCcWsKyziN0eWWetbc9REDca9KH2ZlpCzzrLGn
        cPyoOmxL/vhQsiT5igNJOUnAy4w2/olwASwpdzBrJlqJDVRp7JQTIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T18:17:31Z"
  mac: ENC[AES256_GCM,data:dM98VJFT+6Ce875idm4UeWL9pXrSwvv4YpswHozytrySg48QQajlUVjSjlYXGEBL3AGQwUZ4USITCUG5J+fIWaEIGr+gemUuUJ8ARpWqdKig/G4tJ6LXW7tZiglfKag8iE1d8cMra1Z5LuQ7Es+1rs+DqJxZlXF/50r+ahTieSo=,iv:LyEAR9xV4eeQkUeXDOpyjytyRnsiL08f/ZunwJGjuNo=,tag:mIL+qTyUBEy1BZM0jq81pA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
