apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-dot-keys
  namespace: openclaw-agent-dot
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:VEefwEg+XEohuyu1Xk2dK3QdwsfUSczElV85idFEM6rPmsIOpMAfD0rlCU0Bc5cA+u5Ee6e3w16YPP2bMoGxgkAQ63usu26dLQ==,iv:25bxabNVDQSM13l91nusYfPomHpUreVl9b1j7WEswmk=,tag:gBcwj3PqjbpeKd9oLaOVMA==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:tHu6XiKDSNzSC2lcS5TmRGOmURHoHNnIaqRzigZLMM0=,iv:IXrDl0bwLttFTJb6C0lsLIYQ6fn+3ZlFRGfjKco1+2s=,tag:7uNxd/TM3cFLdM+waJM4ug==,type:str]
  BRAVE_API_TOKEN: ENC[AES256_GCM,data:PR6jG7DJDVDiezUYd+cRa2b2GUQVS29sMPsEvFgjhw==,iv:6CmFcGY6Cmv2gOnPbozI1ZVlxD1sQPImd+ajuVivkr0=,tag:3OtFRFLjq9PveLlSOeGQuA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd3Njem5nclBNNEVCY3k2
        ZEJrS2c3ZUxaQWM1RTh4V1UxNElScWNKMkdJCkRYa25EOExtOW1qRy9iSkErOCtH
        TUoyRHlxY0hLNW1mUE1vOU9yYjFBTlkKLS0tIDBoS0tRL0tWM3h1NDF6OXRMMThx
        SEVncTlROU10c2ZlYXhSV0FrczNVR3cK21Q67AniZFxKdnhbcl0gmr7IpLwTOggk
        2YfFEDiNOeybIVQWdM3sbJoIddnSS9ikXtDmnAYOqC2IR2tUZot9cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T13:38:08Z"
  mac: ENC[AES256_GCM,data:li50ytHHLFmJUbThg9gaHKT5+zo9LctsHTnZqmKBBL1H+9ZMpWklu/PTYCXWa46+aF3jV6aTou75rFs0hA7pmlIlql64S9jpxjI/nHlib7vuFtmLcywBqWj+OuagO5O3zfgIYm5vGcA3OuW81T/cyuUPQl0jVK0NTh3yLqbwFCs=,iv:wLBzE/nEQ5+arjcKmmyBsLW4Cgx4czjM5aKaKx5SLjg=,tag:EF5Rahs2wgzNQHxSSkiryg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
