apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-claw-keys
  namespace: openclaw-operator
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:9EPoonq4XclAbOeuPWoKBbN4FFSeNfdiLJbAYOMfj+OZdDCocvBvw2PordELOnnUSD/q5inud/jmPOIHnr3VXKCkF8ziLTJMCg==,iv:O7BFO1fS/tgSj5Obw0df+qYcEBfbtzhAM/QxDsLbKLc=,tag:dSvtBRLwaWGhXv6jEE2x3Q==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:mJkqUQThL9Bi060z7Rm1Dxq6MAmRKFfFBMy6p9Hopoo=,iv:oeY3L2n5J8hcFaNVaueVUBmkJ8dXn4vgDUExhhtCd0E=,tag:rQibWtejQjFPIniBTI0TQg==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:oQLLsYvhAGKFp8ukwEBQnLtupmoIQIGTP/92nVxMipn/uZVTp0bcpg==,iv:J0eeKwTQgQIBKeLdnRFjXT/mq/BvYqK/uUK3eTZo5G8=,tag:eg7SfK66qg+DR133Rw5gAA==,type:str]
  AGENTMAIL_API_KEY: ENC[AES256_GCM,data:GCgYwZYVRN6kKcNaBtKMq6AG9LRMl7GOg7flP587GASviAT163bPNoR5ogGsqZ/sXUaJp4XZzCQEqLezFjcNXUM+XyR/xhZm+S8=,iv:s7exyAw6GwJJfw0DV1GLoaUlXCXLursWktMVfksdksI=,tag:a5iENyXh3+8nQyt9EQKWfw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd0M3SkFLbzV4TTkyNDdJ
        clAwMnp6ZkNoOWx2V1UzTmV3Q2FVK2lhNDE0CkE2clFodkp4RnJsTm8vRzRjdkdh
        ZTJzYjZqK0JDdGZ3eFcxd2ZmVllvN2cKLS0tIDhqQUUwNjdjeFdzQSt0STFIaWJ6
        OXVKT3cvcWpXZ1c3bnhsQ0x5U01PVk0KMtS8BGO/KSWOiZgxFVwOv94Pce79fcWU
        8GZFN0gZdUyZRCOTQmD4MiEqWSOV3Iq+qvFegSlJziagDQelDmzoAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T18:00:21Z"
  mac: ENC[AES256_GCM,data:X6eNPwGaVz1rrYNjQ/V5aMrAPjizDVv3yC0vZeHW5JZc5pix9yo1A0DOKqGR/1+UCsk/iN4ksfsMCB7jEAS6HWhhl5aF/MQ6oZLkV0hqM/1QHZXuABAN6FlwTeTy3fLgc1kHosK1S4x51l3v3ARaISnzMivIxmWvE8DLAKDxEwc=,iv:6eBt4hgDd8RUDvoRLD0kruXRQsi3vc6wsW1LtCmWn00=,tag:mx9K9W3ARLIxXKAd6xQQzA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
