apiVersion: v1
kind: Secret
metadata:
  name: openclaw-agent-claw-secret-files
  namespace: openclaw-operator
stringData:
  client.yml: ENC[AES256_GCM,data:TA2dYJU8p5KHklc4WzQ93nHP9X4zuz5EzuY5Qs0oAoiGAdMzyDl5t6bL5Fg39mpwat6btpk0qDa1pu38SYT2rTN/hgYigXCbEbffYZm1OAdegrRYPXOO0Q==,iv:d7IAWKSmGpJWhfPlX5z3ACN/5hQmiDF2lXyO5Wv3dCg=,tag:mj7u5rPLIRYGl4X8hRi/pw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcHhoeXdiWnF0bjczWHk4
        cUNZM1JUazNnNXlxS3JOSXREdDBJalg0K1ZrCkM5Q3JQWUFqU1BKMW10c2UrL2xM
        RVlZZkNHZVZkYWc0a0JBUzBVbkdLSDgKLS0tIGZ6NlBFM0Z3RmVQVGdnTW1UOWJl
        SzYyN3UzaGs0YVBqNDhVNTc5M3V1T1kKVkJjkiGl8Gw/3TkSgKWwueoLeAc1fJpu
        mWqJy0zFIIb75kdPHnQkFx2hUtAdBWQMvMyPwxjVIkIYcCeAanxUsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T18:01:14Z"
  mac: ENC[AES256_GCM,data:qVErSMGLDkChzGIVEzRSL2IgvEHnG29ODVdUQzVLelc4XjXF23tVh80fqMVw1aa7mAlZXxctwt7f+uyG8/OI24eWey/HKRg2N6rXPLy9gvYNlooCaDQbFprlSpd8iAv/jaU1cSUsRRTaCtqk9nLyWDFhl+OdCE5LRqWNqeqDbCk=,iv:KiqJqn5YqPhVqMsnMuCmExVFtnlFOJQg1D/J/NK1wso=,tag:valEEaAAtbvw56uIjq6TIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
