apiVersion: v1
kind: Secret
metadata:
  name: openclaw-api-keys
  namespace: openclaw-operator
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:yq7VLW98vgOig7jkTskFnS7ScXijyA42Zi9KhMs7YfCMpJV6PnjQ/dqnGnwiG5LsbqtvtW+acvDHobmXWMs55aKtv3RR227t4w==,iv:89yltALqSEjIXef9Zx4jb1By9c3VIiYlGKifoCHeGbw=,tag:25N9mAXrWEzY1ikjQ1TmRA==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:9DZ8gyL7BJjXZpiv+6rL9w8nt3Yij4QgXi1UuPWu9y0=,iv:AkT2zaRGn9vPuC+29pF2aQZSH5mlUec38JyLQB9s7go=,tag:fXc+BjJjFs8Q2fE23AlSDA==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:Pb5S05Mlqi0OvAqfw43nJ7pxijcCz/mICBndDmkzB2zzHkMcJvjGMg==,iv:7+B/CUj26DQ1BG7/uh+Q1ZbNa8OqvG0QoZ5Nel2/eIw=,tag:EzUEpxsTq0IwoWaN0+BkOQ==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b1hleHFGUUsxMHJPdG1m
        MTQ0ZzlORU9vbEVQODZ5aXN0OVVKZ2xITm5nCnY3ODN4WDc2ZTE5QllZUFRqSjJ6
        M1VRNzFaM0QxNFl6V2VBdEwyUHhSanMKLS0tIDJEZ2lnNzF5WFBVNWVUeHhRYTdY
        WkNmMS81b243Tk9Ick9LSm5vRTBBK0EKxKhDSdzb0BMKuzWseWUM7C+HNohcxpE1
        xBwCPU76tRX9SmnJH8+YF+iIeJDJI096i5LavOfp+/yoJhpRo+01GA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T00:28:40Z"
  mac: ENC[AES256_GCM,data:d/riPmMwzXlMeV2Fc/vlCvxwwItnmnr0KfgXmtH7eaEDXCgugbrOHNfxj+Rniv+uwntlTDDFTrd8enNyxMQaSPt3EvivcRjIUSoRkkYVGsowkppcVEDhryi7b4yaSIGBGoY2cxDh2XAYfqGcJ3RgBqhweTZMZMRHopNvVt/zcYQ=,iv:aEa1cC90JJWhY54kku7DKiO4oTMgyIpaACa7KWT1Zt8=,tag:P5LZNswoNvl22vST0DbyoQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
