apiVersion: v1
kind: Secret
metadata:
    name: openclaw-agent-claw-keys
    namespace: openclaw-operator
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:8m+BhkNLkand4dGfljiNXP7couCBSs46ZUcCL+ccJQRCW7VWWfovBooJSSp9fZzzLOxZ5kHHlzdt8yAq29DHantK6ORI3SoQXg==,iv:5cCtB1FWEvwSq5U+Q8ChPXw0Paggq4ettrHv4TJc5qs=,tag:kvDERGfbh8C4q2ghL87gHA==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:niY6WmMACqetC4p9g4ydwK9StvmyIgrz,iv:Twar4Zs9MoLX4RxEIH3wLE2WEdnpX596TgN9RgzYb8w=,tag:/oxuXlXHGAp3ER5sGMSoLA==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:kfTATz1qJf1y95Lry1kMtmNszvnc3dJD+aUm4Origc0mv7boah8fqg==,iv:h+eReThMpUuDYkja8Q7jopidgUFyVmIrhZQr3OUYbus=,tag:4SECME0IRJ0QB0xy/WC3Eg==,type:str]
    AGENTMAIL_API_KEY: ENC[AES256_GCM,data:V5LXTqjsUsFQJEgg37PD1/8O4y/hhhM8AqD3Qly5/kBrTXlDvuNIjXhNF4eKsVIRe+E75K4KLDzM3e0pZ85NmHV6rzmzTO/UCXw=,iv:FtaXukPlWuqRFJVHMCkjrXwGV3w5OIt0WsKfuzQtcSA=,tag:r4yn8KiR7r0/dJNiaI3isw==,type:str]
    BRAVE_API_TOKEN: ENC[AES256_GCM,data:R4kgvQ8W+5blFMCD2JhBEI+TlryzhsEvUM2XXQX2iQ==,iv:zuunCGdUFXQYQx3x5hLvj8m/Cy+CDTEZJOPilmsZC4k=,tag:KgZw54wRffoUWZyZulmv+w==,type:str]
    GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:tlqQBHhteSUI5vFC+Q==,iv:A2pjzHM2JjiVLrvirXmge2BG82dovLQX/8gzAt3jJGQ=,tag:nmsOvmYVmVBeXw/BSa0hYw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdW03dC9NeUU0K1krbWFF
            OXY3YWVab1J3emZxMHVVdTNOR3dvVWxSUUZvCnppQW9SeGhvcGxPUHhCNFVuQm0x
            MCs4ekdIS3cvQzJrVjJsenVUbGxwMFEKLS0tIGp0QVRuc2tLTDY2TkRBcmxSWDlw
            QzBpYzV4ZDdhcFBFc1IrOFc4cEhoUUkK4XH+ooj0aeS6VRVjzhLtWG8+q/4yd54d
            XSauB3k01xPQgCmkZ3IARArCIQi5LCxlJZ6qcQ4K1egCAm02Ze2VQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T01:34:42Z"
    mac: ENC[AES256_GCM,data:K87rqlBcr5j+115s9TV/KNo/upLtJ8Jo6bEEIf/cAuTqWsiUVLA1Hei8PDMiamRpxII+byPqMp//eax7VQnWcwDBGUHf5z+WU2ppBMHT1+oXMHA3JMh3H8p25ozW7q5CwTWlcWruPPx+QiWE89jPZ0dIqFa9Aqve0GRWg+zipIo=,iv:9mVuEuBFDSkq7h1pKv+jvs/N8nolgbfoE5RuQfkZBG4=,tag:JmocpYlyr0vWr3qJ5/IiCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
