apiVersion: v1
kind: Secret
metadata:
  name: openclaw-api-keys
  namespace: openclaw-operator
stringData:
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:oKDKg2sweIkPtUtRBBZj12HVJH7QQFbZUmh63c8F5RH4zxGKpxUHRvisrU/M3A3lK1esdlebeCh9LCDLfcrYUF5shZQsopVlPQ==,iv:9wBIFDazxljgkRhyjXY/3Q7Af1SQYrrUC+inTo01fs8=,tag:8+oIZd+KhSPclKUQcAmiaQ==,type:str]
  MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:QTCm9p7D6iPuJL2bQp5E+oRoglJTkU4C4lvd5j8KBes=,iv:O1Z44g320vMBy/FHr/tQVG0aMx/xMP3T4kkPWdqMPmc=,tag:RJFxukapupZSKGMIeGZmFw==,type:str]
  GH_TOKEN: ENC[AES256_GCM,data:WCGg6LT+p/r3P08I4foayiU6XUfEcBVUhyz9sA6uPPSojM3Ra6452g==,iv:YyB/LTJ1w3B0RjfqcevrcI6Oq1JUw5EYFmcP5i7MKAk=,tag:CBKQZgel4BbO/BrcSafT7Q==,type:str]
  AGENTMAIL_API_KEY: ENC[AES256_GCM,data:wvuUwSmLNPtMM5LOUHvm4AQ2YmQJRkwuwL31YxC/ZWnDpAuO4rKeQYJUUtgCPtzFRxADjOYfkGYc+aQZn838TlYE7n274JK/H94=,iv:vgwkhr2Lzy7c1MS9tYzaBv4GClWCnVQfgw7iFX/nq9A=,tag:i7x11TaG/I1r1h/uyGmiHA==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ci91REQxVVV2QXV5UkdS
        Q1ZDVGJIY1BlVXQrU3djVWNpemdLTFN0YmhvCjUxZ3FrUEVLRXI5TmpSRjFNWkNa
        U0loMlk3QVdjSjdJQnIrU2tPcGc5Z2MKLS0tIHZ4L3J5TGhER25VR25taHFRU3FG
        UHpqcGxMR1puM3hEOTlQazE3T082NjgKDEDNFSH1/YZiICSPiAJiyryvKEHLI7e8
        n+2OHn5XAZMS/rJg4RBmSrf4Ss8Du2m1p8LXyWxulFucfQ0YVTVx4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T01:06:25Z"
  mac: ENC[AES256_GCM,data:ZPcKQTVhNYMttEO+QWjE5nObzabNgnAlLYyyLACvhl2aMGDBYa0dh+9QhfURekHz69PNngsdV03l/Y6iUj5kiU4RvuQwU16er40PDFtVcQpXBPsduli2b2YeZDEUpPeXGB//Feu24hWSwFofhPS9XkSYkYJ21kLJekgAisx57gM=,iv:AcR7oq5xGOfe++h9tfhrvwBalF2QqYXhJaG7bx70xfQ=,tag:4Vo9/mTu46vTkwWXpqY6DQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
