apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: atcr-registry
    namespace: tranquil-pds
data:
    .dockerconfigjson: ENC[AES256_GCM,data:NaA916QZfYuAQPkePXEyneAIwb5Ks9pyTtChsfzf4/NxpA1j3KWgKLrwrEWdN8dGuDUON5g0OaOKLueLASaD7a1xfH2PU47mhEqg2gP6qthEL2E+905Pa/zLisM9NKGJuLoqAJ8Ll0NKnGcda4+L1oRc9k36tWnS2swp0a1yLK8C6nvRS4ATD5T/qwdKrTMNB7OWVPZ7xqDL411cMJiD1X3s43R7aaZOx38qzZyA+YvM53LqgjRGbkssdYHwGSCRhHJmBYZJFWtGHgNGKL/PUQ9SJIXHuyLZtEAqC//adDGMCEzNN3Hhvg==,iv:f4/i/a58L/NW4sgmB0bY8/U52H8SHomy0OWZLu24upI=,tag:QUc112aHIv6g3frprtA1MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMzIrbzZ1eVdVR21SN0pu
            WUdvVXl3ZjFPRTZEZk1mMDBzMGFpcEYyYlFrClVXZ3Z4UXY5bmQwbENpcHdRblV6
            NkRqQ3FpZ2xmaFVNem9GT2VIQlp3clEKLS0tIDJrTVc4WVVsRHlYRkUwUHlQcnJj
            SXFJMnljaVRMTTkvSzQ1OXJTUlRVNmMKDVqQs7NueLHZb+Xl52R7py3mQF4Tp1R5
            v6YP2aAbudYXragfRWZ/M90tb0L3f11smcZ0wxf6LdJG7IB6NKMPDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T19:28:46Z"
    mac: ENC[AES256_GCM,data:pTxk0CTOFV/ypCkfXCOp8JubngNn1AJpHUlof+vpdS8YlNGSqPze9qWzokgB0ksw2df3pgD1h2CuYV6+TT3D4AD1N/qlZEe+ThTDuj7enB4bbQ/7l7eb0F6GhZIgdTn8Us/zg9CC5wgglSnoHsPYuMxk6CF1gYXHFzj2s1VQWzU=,iv:mQ4CQa8P7kWckAbWgW8qYwbH01V4OAd4u0wk/r/iALI=,tag:6gF5VlS+1QdoOJmdMChilA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
