apiVersion: v1
kind: Secret
metadata:
    name: tranquil-pds-secrets
    namespace: tranquil-pds
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:eG0RyJ7jgP+UEfVGdJGS5A+jcJ8bHu1omx5CBZn/wSBU/i0yOdzTjUgRFpR181uqiGBu9v0gALr0tcCGWL7PQBNUetThLIxS8UVENvvgmG5pWIuz+Zi43FC40U4bcMGTAjWbG838kg7ar1YJo1R34O+uVA==,iv:vKLiXlPC/h65LW96QDkDRbjYKjqRAunmAqUK4M/CPtg=,tag:+OmG8lJPkfUy8KPrCjg/xA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:L4yBShpCcaagp5b/RrFSKZC8ck26boYI36oR31duteOgM8FX3Yd5uiejjLDon9LlvOjl7FDF3r3PpiH+Gw5brA==,iv:0/54y+j8fXJ7vG532pl/DbksvXIX/V4dstU+jt/ssTA=,tag:6/Nsoq75WmILI12QelQWMw==,type:str]
    DPOP_SECRET: ENC[AES256_GCM,data:26qEZLdltI3EPxzRh0eq7QMBWpfgpxUj5EuaD6D0eQVhDuw4dJlHjIp+hTt5fIb6ZnpBlGZYOaoKgZotI3B/jQ==,iv:ds5fdRqo+CxMay9ZzzsE8gPXR6EJa6K5QZym//tnjEk=,tag:Zjc7vHKt1ODyhv+J1zSNZw==,type:str]
    MASTER_KEY: ENC[AES256_GCM,data:17yM2IlCegHAY7fPdRCHOaL3jP2udDB/VgyA1CK/9cuT43ggIMkiZJkFqsBysVsh28GiXZkgO/UNSCN3g6pHow==,iv:z85EuC73mEiT5zH3kkJewJuXwRK0ou5vIQ9WGNvHiGg=,tag:7+drLUsDxFPE1+TH8KH1qg==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:bsEaxfnrqZiDtHlVFF6h,iv:+u7pJP28NfisMBGn8IjA1nlYA043Vos4F/WPoIZP5E8=,tag:Ad4AqjaTeFcRV9lgymKckQ==,type:str]
    MAIL_SMARTHOST_HOST: ENC[AES256_GCM,data:LGP3PrURhWNVipB6AkojLw==,iv:2HeWsb7O4bGB3ZeKwi8sG8HO6F7/g1yj+U+Qt6fDX/c=,tag:bNBXBCCPGgC6DVuhIG+NyA==,type:str]
    MAIL_SMARTHOST_PORT: ENC[AES256_GCM,data:AvH3,iv:+qmW1e6mAImAYhGSYQp5ZAjhjP4IYlnKjSrXlu2zMFY=,tag:tyfk368VwbotaIFGedq0DQ==,type:str]
    MAIL_SMARTHOST_USERNAME: ENC[AES256_GCM,data:/DR7rcnev/6bKwVZkoLD,iv:vKfPRDiegcjZ/vaAXc3HalHQcLtoZLxYG10FhriWgLc=,tag:tfCbwFO0FLV1sCwrfIBgYw==,type:str]
    MAIL_SMARTHOST_PASSWORD: ENC[AES256_GCM,data:K4jefQ6+e0dsVb9RK3Rl7A==,iv:9codPdKV+h5GIKars4KIGNglz9ZeBhEQRGzjuqVB4Cg=,tag:P6njaSV2YM1XYVseVV+asw==,type:str]
    MAIL_SMARTHOST_TLS: ENC[AES256_GCM,data:n0eDIQpkk7o=,iv:tcCj/ZnxgKfJNrotQuaqgx1td+/jKJoUQPq9NGi/NYc=,tag:09cB3JuYXHCHPqpUET9BTA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjfnjke9r3pydyllm9wm76kk6mzwg26rhk4s4jwzavh9xle7ca7qgk20z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWDJpWDNzV09IWTFGNEhU
            dnlNZk41cGNsOVRhaDZpNnhEazlJMVhYZWlBCmpoV013LzNvMHUvUG5JWDYyckdP
            WktDemE1Y1UvV08xUEFycGMrT1BSaGcKLS0tIEJjcXJwcUdyRzA1MGZUYndyNWl6
            MUl4QW94WWF5dVZOQzRHdXZXZHVwa28KgCH4WwNqjWlKhEq+kZJfFb6kdhr00oJy
            60kYsE28XQCRgbEVpfVQketr8AgWL6/n+mji+KJTYMzYeSlV3kUW+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T19:51:14Z"
    mac: ENC[AES256_GCM,data:/hKDhe2F2TJpItWe4kNPQ9ajsK2aRYX4+G9mpgnS57mACwJv906sGXVMGuD+ZUpWT0daTWhafbZvSYrMdvFlX+SsviNkZrv0MkvtM7ZSUHom/C4WDBP2Z92ct7Og/UaJ8Yl9r8u+uxyXenMrCsn1qjhHoKlKszxyyk+Hh+joEB4=,iv:PybGJsioqukJWyrrepjov3peoXKSeZ1Hk/VGmuAobqk=,tag:80UShmYYVAqoyLqfDUsryQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
