apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: intel
spec:
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.X.X
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: gpu-device-plugin
  values:
  # https://github.com/intel/helm-charts/blob/main/charts/gpu-device-plugin/values.yaml
