apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: rewrite-dockerhub-to-harbor
spec:
  evaluation:
    admission:
      enabled: true

  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]

  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >
          Object{
            spec: Object.spec{
              template: Object.spec.template{
                spec: Object.spec.template.spec{
                  containers:
                    object.spec.template.spec.containers.map(c,
                      Object.spec.template.spec.containers{
                        name: c.name,
                        image:
                          c.image.startsWith("docker.io/") ?
                          "harbor.tartarus.us/dockerhub_proxy/" + c.image.substring(10) :
                          c.image.startsWith("ghcr.io/") ?
                          "harbor.tartarus.us/ghcr_proxy/" + c.image.substring(8) :
                          c.image
                      }
                    )
                }
              }
            }
          }
