apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: rewrite-deployments-to-harbor
spec:
  evaluation:
    admission:
      enabled: true

  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]

  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >
          Object{
            spec: Object.spec{
              template: Object.spec.template{
                spec: Object.spec.template.spec{
                  containers:
                    object.spec.template.spec.containers.map(c,
                      Object.spec.template.spec.containers{
                        name: c.name,
                        image:
                          c.image.startsWith("harbor.tartarus.us/") ?
                          c.image :

                          image(c.image).registry() == "docker.io" ?
                          "harbor.tartarus.us/dockerhub_proxy/" +
                          image(c.image).repository() + ":" +
                          image(c.image).identifier() :

                          image(c.image).registry() == "ghcr.io" ?
                          "harbor.tartarus.us/ghcr_proxy/" +
                          image(c.image).repository() + ":" +
                          image(c.image).identifier() :

                          c.image
                      }
                    )
                }
              }
            }
          }
