apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: hermes-operator
  namespace: flux-system
spec:
  interval: 15m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/hermeum/charts/hermes-agent-operator
  ref:
    semver: "0.5.1"
