apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pgo
  namespace: flux-system
spec:
  interval: 15m
  url: oci://registry.developers.crunchydata.com/crunchydata
  type: oci
