apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 67.X.X
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: prometheus-operator

  values:
    grafana:
      enabled: true
