---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-middleware
  namespace: prometheus-operator
spec:
  redirectScheme:
    scheme: https
    permanent: true
