apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: prometheus-operator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: snmp-exporter
  ports:
    - name: prom
      port: 9116
      targetPort: prom
      protocol: TCP
