# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  backend "s3" {
    region  = "us-east-2"
    bucket  = "tartarus-infra"
    key     = "terraform/mikrotik_router/terraform.tfstate"
    encrypt = true
  }
}
