apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sillytavern-config
  namespace: sillytavern
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
